### ISSUE TITLE
Android: Prevent screenshots while passwords are shown

### ISSUE THREAD

**Issue by hpoul** [authpass/authpass#100]
Should probably be optional in the prefernces.
There is an existing flutter plugin: https://pub.dev/packages/flutter_windowmanager

**Comment by Turux** [comment]
This being a password manager I believe screenshots should be blocked for the whole app. Usernames can also be sensitive information.

**Comment by hpoul** [comment]
@Turux this is now implemented, for android only. And still off by default, needs to be enabled in the preferences.
I'm not sure about this.. i feel it is awkward when invoking the app switcher and the app is just black.. so i'm not sure if this is the correct "default" behaviour, especially since passwords aren't shown anyway.. and if usernames are sensitive to you, you might want to mark them es "Protected" as well, so they are hidden, just like passwords..

anyway, now there is an option to disable screenshots on android..  it's just not on by default.
