### ISSUE TITLE
iOS: Implement Biometrics (Face ID)

### ISSUE THREAD

**Issue by DakJack** [authpass/authpass#101]
It sure would be nice to implement face authentication for iOS devices that do not have a fingerprint scanner.

**Comment by hpoul** [comment]
@DakJack unfortunately i don't have a face id device and the iOS simulator seems to be quite buggy regarding Face ID. I think I found the problem (missing plist entry), I have uploaded a test version to testflight which is under review right now.. maybe you can give it a go: https://testflight.apple.com/join/3CC54i3V should be ready in a few hours, once apple has approved it. (1.6.4 build 1266)

**Comment by DakJack** [comment]
Ope,
I see I submitted app feedback before the version you mention was published. 
Please disregard. 

Thank you for the prompt development. 

-Dakotah

**Comment by hpoul** [comment]
No worries.. but since you've now installed testflight, you should receive a push notification once apple has approved the beta version. thanks for testing

**Comment by hpoul** [comment]
Fyi, beta version had been approved, you should be getting it now via testflight

**Comment by DakJack** [comment]
iOS Face ID is confirmed working using build 1266. 

Thank you.

**Comment by hpoul** [comment]
perfect thanks.. so i'll just publish 1266 right into production 👍️
