### ISSUE TITLE
Adding a custom field wipes a new entry

### ISSUE THREAD

**Issue by Turux** [authpass/authpass#106]
Hi there,
When attempting to add a custom field to a newly created entry, all the previously inputted fields gets wiped apart from the password.
I have experienced this issue both on Android and on MacOS.

How to reproduce:
1) Create a new entry
2) Fill username and password
3) Add a custom field

App version:  1.6.4+1266
OS: Android 10
Device: Google Pixel
Source: Google Play Store

Current workaround:
Save the entry before adding a custom field

**Comment by capruro** [comment]
Same issue faced in iOS as well :(

**Comment by hpoul** [comment]
thanks for the report, should be fixed, available in the next release. https://github.com/authpass/authpass/commit/99d8307e139a134544b684728905f8c5bd361af7
