### ISSUE TITLE
Password reveal triggers keyboard on Android

### ISSUE THREAD

**Issue by Turux** [authpass/authpass#107]
Pressing inside the password field to reveal it opens the keyboard on Android. 

I have the feeling this is not the right behaviour as it can result in accidental password edits.

Alternatively, would it be possible to ask for confirmation prior to a password edit?

**Comment by eL-Prova** [comment]
Similar experience on iOS, See https://github.com/authpass/authpass/issues/109

**Comment by hpoul** [comment]
@Turux @eL-Prova to be honest, for me displaying a password is a rare edge case.. since all my passwords are auto generated, there is no way i'd try to type them.. simply copy&paste them (swipe on the entry to either side of the screen to copy).. also did you try the 'Present' option from the dropdown? it shows you the password in pretty large letters as well as a QR code.

**Comment by eL-Prova** [comment]
@hpoul good case, but I work a lot on my computer, but keep my passwords on my phone. In this case I type my (generated) passwords from my phone to the computer for example :-)

**Comment by hpoul** [comment]
@eL-Prova got it, how about the 'present' option? that's basically why it's there :-) I guess it could still be improved, with even bigger font, and smaller QR code.. 

![2](https://user-images.githubusercontent.com/313066/87410436-990a3180-c5c6-11ea-9fe8-6bf0e29fedc8.jpg)

**Comment by Turux** [comment]
The "present" option can be useful, thanks for pointing it out! 
I still believe that the current behaviour is wrong though. If the app states "Click to reveal" this can confuse the user, as instead it edits the field. Can I suggest to either change the behaviour or change the label to something like "Click to Edit"?

Also, OT, but the message is very hard to read.
<img width="339" alt="Screenshot 2020-07-14 at 11 54 29" src="https://user-images.githubusercontent.com/35221455/87412138-eedfd900-c5c8-11ea-9ec2-db13f2d7aafc.png">

**Comment by capruro** [comment]
I agree with @Turux the text "Click to reveal" is misleading, it's supposed to show the password only, not actually edit the password.
There are a lot of cases where you actually need to see the password, as I'm using keepass DB not only for browser password but also for PIN, application password where there is no copy-paste integration and other cases where I just want to save something not in clear text.

**Comment by hpoul** [comment]
i guess that makes sense.. i could also imagine simply replacing password entirely with just buttons like 'Reveal', 'Present' and 'Edit' .. 
the idea was just that it would be cool if it "looks" like it's just hidden .. but it's faked anyway.. and even if there is no password, it would still look the same, which bothers me as well..

do you think it makes sense to have the difference between 'Reveal' and 'Present' (reveal would be inline, read only, vs. present the big font modal overlay)

**Comment by eL-Prova** [comment]
@hpoul I suggest to make it KIS, Keep It Simple. Edit by tapping so you make it an explicit action, hit the input shows the present view. In that case it is revealed. When editing your password will also be revealed.

**Comment by capruro** [comment]
I would suggest to have a readonly interface in the first place and then have an edit button to make changes. It shouldn't be easy to make mistakes, also because I don't see a password history yet.

**Comment by hpoul** [comment]
> Edit by tapping so you make it an explicit action, hit the input shows the present view.

i don't quite  get the difference between editing and presenting in this case? Where do I have to tap for each?

@capruro yes, password history is written, but there is no UI for it yet (#92). I'm not sure about having an explicit "edit" mode, especially for normale fields, tapping into the field is already pretty intentional. but I agree with preventing mistakes - #91 is for improving the revert/discard workflow.

**Comment by capruro** [comment]
> password history is written, but there is no UI for it yet (#92)
Good to know

I would prefer to have a read only mode where you can only see/copy the data and on password filed there should be "Click to reveal" and presenting on corner.
Then an edit mode where you can tap to reveal and edit the password field and generate password on the corner.

**Comment by hpoul** [comment]
I move "read only" mode into a separate Issue #148 with a more descriptive title. Feel free to comment your suggestions about a read-only mode there as well. I'll close this issue.
