### ISSUE TITLE
Feature request: Hide the 'regenerate password' shortcut

### ISSUE THREAD

**Issue by Turux** [authpass/authpass#108]
I found that having the regenerate password shortcut in a protected field may result in accidental presses, specially on touchscreens.
This is particularly true if one has to press on the field to reveal it.

Wouldn't it be wiser to hide it in the side menu?

**Comment by hpoul** [comment]
it took me a while to understand what you meant :-) i agree, i've changed it to be only visible if the password field is empty:

![2020-07-17 20-34-46 2020-07-17 20_35_21](https://user-images.githubusercontent.com/313066/87819738-0e972b80-c86d-11ea-8279-6fac83d17cd9.gif)

fwiw, I slowly warm up to the idea of making a separate view/edit mode.. 🤔️ anyway.. this is a bigger change.. for now this must suffice :)
