### ISSUE TITLE
Tighten Google Drive permissions?

### ISSUE THREAD

**Issue by hackel** [authpass/authpass#111]
Currently, AuthPass requests *full* access to Google Drive, displaying a big, scary warning.  Is there a way to limit the scope of permissions requested?  Ideally I would like to only share a particular file with the app like I would another user, but I'm not certain if Google supports this.

![image](https://user-images.githubusercontent.com/583677/87582519-1e154980-c6a0-11ea-9cd1-054985ee17bb.png)

This is probably fine if you examine and compile the app yourself from source, but for anyone who uses a binary distribution, the app could literally do anything with their data, send it to any remote server, etc.  For a password manager I'm sure security is a priority.

**Comment by hpoul** [comment]
Nope, I did not find a suitable permission. It is either just requesting access to the "application" folder, (which is not very user friendly imho as those are completely separate from the rest of your google drive) - or "all" data.
There is a web API "Google Picker API" which allows picking a single file afaik.. but integrating this into a cross-platform client application seems pretty impossible to me. Especially implementing 5 different platforms (ios, android, linux, windows, macos) with 3 different cloud providers as a single developer is not very scalable.

So unless somebody comes up with a better idea, i fear it's either all or nothing, sorry.
