### ISSUE TITLE
Crash on clicking 'Load from Dropbox'

### ISSUE THREAD

**Issue by hgohel** [authpass/authpass#114]
1. Install AuthPass-setup-1.7.1_1324.exe on Windows 10 version 1909 (OS Build 18363.959)
2. On first launch click on 'Load from Dropbox'
3. Instant app exit

Repeatable on subsequent launches

'Load from Google Drive' crashed in a similar way the first time.  However after this occurred once, subsequent times it did not crash when choosing 'Load from Google Drive'.  And after that 'Load from Dropbox' also stopped crashing.

Looks like the authentication piece for both Dropbox and Google Drive isn't implemented yet, but want to report the crashes for investigation.

**Comment by hpoul** [comment]
thanks for the report. can you please try build 1333: https://data.authpass.app/data/artifacts/AuthPass-setup-1.7.2_1333.exe

I will have to update the link on the website i guess.. is there no update notification?

**Comment by hgohel** [comment]
@hpoul The updated version fixes the crash problem, thanks.

Yes, a dialog popped up asking if I wanted to allow automatic updates. I din't enable automatic updates and just dismissed it.  If that dialog was meant to convey that there was an available update, I guess I didn't read it closely enough.

**Comment by hpoul** [comment]
@hgohel no, that popup was just to confirm update checking, without update checking there is obviously no update dialog :-) I highly recommend enabling it though.. but there is no way right now 😅️

anyway.. so is there still a problem with the dropbox authentication without the crash?

**Comment by hgohel** [comment]
@hpoul Crash problem is completely fixed. Closing issue.

**Comment by hpoul** [comment]
@hgohel great thanks 👍️ if you experience any other issues, please let let me know.. in the meantime i have created #115 to improve to auto-update prompt.. (and #116 to remind me to make this automatic 😅️)
