### ISSUE TITLE
Fastlane changelogs not updated

### ISSUE THREAD

**Issue by licaon-kter** [authpass/authpass#119]
https://github.com/authpass/authpass/tree/master/metadata/android/en-US/changelogs

**Comment by licaon-kter** [comment]
Partially fixed in https://github.com/authpass/authpass/pull/121

I dunno 1.7.1 versionCode to create that too.

**Comment by hpoul** [comment]
Right now copying the changelog over is a manual process from the main changelog https://github.com/authpass/authpass/blob/master/authpass/CHANGELOG.md I have created one for the latest versionCode now: https://github.com/authpass/authpass/blob/master/metadata/android/en-US/changelogs/140.txt

Actually I wasn't sure if it was ever used to be honest. I've never seen a changelog on the fdroid website, and AuthPass never showed up as "Last Updated" (as far as I can tell). How exactly is the process working? Is it looking at the file at the time of the build? Is it going through all .txt files up until the current versionCode, or only looking at the last one?

thanks for your help

**Comment by licaon-kter** [comment]
Grabbing from HEAD on new app version publish iirc.

**Comment by licaon-kter** [comment]
:+1:
