### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [authpass/authpass#120]
v1.6.4 with 1.17.1
or
v1.7.1 with 1.17.5
```
2020-07-27 13:48:52,742 DEBUG: buildserver > Running "flutter pub get" in authpass...
2020-07-27 13:48:52,743 DEBUG: buildserver > Because no versions of flutter_svg match >0.18.0 <0.19.0 and flutter_svg 0.18.0 depends on xml ^4.1.0, flutter_svg ^0.18.0 requires xml ^4.1.0.
2020-07-27 13:48:52,744 DEBUG: buildserver >
2020-07-27 13:48:52,744 DEBUG: buildserver > And because every version of flutter_driver from sdk depends on xml 3.6.1, flutter_svg ^0.18.0 is incompatible with flutter_driver from sdk.
2020-07-27 13:48:52,745 DEBUG: buildserver >
2020-07-27 13:48:52,746 DEBUG: buildserver > So, because authpass depends on both flutter_driver any from sdk and flutter_svg ^0.18.0, version solving failed.
2020-07-27 13:48:52,746 DEBUG: buildserver > pub get failed (1; So, because authpass depends on both flutter_driver any from sdk and flutter_svg ^0.18.0, version solving failed.)
```

/LE: disabled for now https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7163

**Comment by hpoul** [comment]
Yes, we could just go with the current flutter beta.. i can probably send a mr later today..
Btw would it be acceptable to just download flutter through the build script, then i could just use the same script for all releases https://github.com/authpass/authpass/blob/master/authpass/_tools/install_flutter.sh but it uses the binary release of flutter

**Comment by licaon-kter** [comment]
Umm what's the difference? We use the binary currently anyway, right? https://gitlab.com/fdroid/fdroiddata/-/blob/f9687b37cb0230fc4330f5b7ccc2c4315b5c3dea/metadata/design.codeux.authpass.fdroid.yml#L200

I guess it's okay

@bubu @eighthave @rudloff thoughts?

**Comment by Bubu** [comment]
Downloading flutter in the build script is okay, but please add checksum verification for the downloads to your script.

**Comment by licaon-kter** [comment]
Random example: https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/se.manyver.yml#L1464

**Comment by hpoul** [comment]
thanks, I think i figured it out, at least works on my CI

https://github.com/authpass/authpass/blob/de77203d89511f12ff194ef34a0582923bb62b4d/authpass/_tools/install_flutter.sh#L44-L56

I'll create a MR for the metadata later, should be pretty straight forward.. although i'll probably just install into into a local ./tmp/ directory, no need to sudo it globally.

**Comment by hpoul** [comment]
here you go: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7166

**Comment by licaon-kter** [comment]
:+1:

**Comment by licaon-kter** [comment]
https://f-droid.org/wiki/index.php?title=design.codeux.authpass.fdroid/lastbuild_141&oldid=274926

**Comment by hpoul** [comment]
damn.. thanks for the heads up.. i've prepared AuthPass for localizations which required some weird workaround in the download script.. which didn't work well with relative paths.. I've fixed it in master, will probably release a new version in 1 -2 days, then it will be fixed.

**Comment by hpoul** [comment]
fyi, it's now fixed and i just tagged `v1.7.4` and updated https://data.authpass.app/data/fdroid-version.txt - Let's see when it is picked up 🤞️

**Comment by hpoul** [comment]
looks like i've accidentially committed a binary somewhere.. i've deleted it and created a new tag.. let's hope this works..

**Comment by hpoul** [comment]
@licaon-kter could you take a look at my MR https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7286 it updates the release tag naming so I don't have to change the whole release tag for all platforms if I have to fix something f-droid specific. thanks.
