### ISSUE TITLE
could not paste auth code in linux

### ISSUE THREAD

**Issue by aahnik** [authpass/authpass#122]
![Screenshot from 2020-07-31 18-43-03](https://user-images.githubusercontent.com/66209958/89038377-db20ca80-d35d-11ea-8c11-053833ad2a0d.png)

**Comment by aahnik** [comment]
paste not working tried with 
ctrl + v
ctrl + shift + v
mouse

**Comment by hpoul** [comment]
Have you tried clicking the copy/paste icon next to the input field?
Which version of AuthPass are you using, and what Linux?

**Comment by aahnik** [comment]
no i am sorry
i didnt knew that was copy paste icon

**Comment by hpoul** [comment]
To be honest that button is just a workaround.. the goal is still that all the other paste methods work as well.. but flutters linux support is still in an early stage.. expect big improvements there.. are you using the version from the snap store, or the tar.gz? Make sure to stay on the current version.. I'm still not sure how to best roll out updates on Linux :/
