### ISSUE TITLE
MacOS: Unexpected error: NoSuchMethodError: The method 'markNeedsBuild' was called on null.

### ISSUE THREAD

**Issue by 0-wHiTeHand-0** [authpass/authpass#124]
Hello,

After using AuthPass for some hours, I get the following error when browsing through the items (not always, just sometimes):

Unexpected error: NoSuchMethodError: The method 'markNeedsBuild' was called on null.
Receiver: null
Tried calling: markNeedsBuild()

You can see a screenshot below:

![Screenshot 2020-08-03 at 00 04 22](https://user-images.githubusercontent.com/12022972/89147956-e9b5e000-d51d-11ea-87ad-9fd451d13a1a.png)

Thanks!

**Comment by hpoul** [comment]
To be honest, I've seen that one as well a couple of times, but was never able to reproduce it. Any hints would help. Are you doing anything specific when that error pops up?

Can you please share your log at ~/Library/Containers/design.codeux.authpass/Data/Library/Caches/logs/app.log (either email it to support@authpass.app or if you don't want to share your full log search for 'markNeedsBuild' which should get you to the error message.. and just include 5-10 lines before and after that one..)

thanks,
  Herbert

**Comment by 0-wHiTeHand-0** [comment]
Nothing specific, just going through the items. Here you have some logs from the app. I realized there were 2 different error logs because of the markNeedsBuild:

The following appears once:

2020-08-01 16:09:13.450397 SHOUT main - Unhandled error in app.
### NoSuchMethodError: The method 'markNeedsBuild' was called on null.
Receiver: null
Tried calling: markNeedsBuild()
#0      State.setState (package:flutter/src/widgets/framework.dart:1260)
#1      _CredentialsScreenState._tryUnlock (package:authpass/ui/screens/select_file_screen.dart:841)
<asynchronous suspension>

And the following appears twice:

2020-08-02 23:09:53.547701 SHOUT main - Unhandled error in app.
### NoSuchMethodError: The method 'markNeedsBuild' was called on null.
Receiver: null
Tried calling: markNeedsBuild()
#0      State.setState (package:flutter/src/widgets/framework.dart:1260)
#1      KdbxObjectSavableStateMixin.saveCallback.<anonymous closure> (package:authpass/ui/screens/entry_details.dart:224)
<asynchronous suspension>
#2      _logger (package:flutter_async_utils/src/future_task_state_mixin.dart)
#3      TaskStateMixin.asyncRunTask.<anonymous closure> (package:flutter_async_utils/src/future_task_state_mixin.dart:31)
<asynchronous suspension>

If I can reproduce it consistently I'll let you know.

**Comment by hpoul** [comment]
fyi, I have fixed those two errors https://github.com/authpass/authpass/commit/5240f2720b0756fff3730f65389820daace24451
the second one happens basically when you make changes to a password entry, click 'Save' and then navigate away from that entry. Will be part of the next release.

**Comment by 0-wHiTeHand-0** [comment]
Great, thank you!

**Comment by hpoul** [comment]
The fixed should now have landed in 1.7.3, let me know if you experience any further errors. Thanks
