### ISSUE TITLE
Google Drive Provider Error: MissingPluginException

### ISSUE THREAD

**Issue by pascencio** [authpass/authpass#132]
Hi guys,

I tried to use the application with Google Drive key file, but in the login process get the following exception:

https://gist.github.com/pascencio/5657b60f7c138b899b36aa3ca84f793a

I'm using `authpass-linux-1.6.3_1201.tar.gz` versión on linux.

Here leave my OS information:

`Linux 5.7.15-1-MANJARO x86_64 GNU/Linux`

Great tool congratulations!!.

Thanks in the advance!

**Comment by hpoul** [comment]
Hi,
can you please try the 1.7.5 release: https://github.com/authpass/authpass/releases/tag/v1.7.5
I should finally solve #110 🙈️

**Comment by pascencio** [comment]
@hpoul Thanks, now works perfectly!
