### ISSUE TITLE
Unrestrict max autogenerated password

### ISSUE THREAD

**Issue by exalented** [authpass/authpass#133]
I like to set passwords to be very long. Is this a feature that is in the planning stages?

**Comment by hpoul** [comment]
@exalented what do you have in mind? :-) The current max is 40 characters. Not sure how to build "unlimited" into the UI :-) how long would you like?

**Comment by exalented** [comment]
I think 128 would be reasonable

**Comment by hpoul** [comment]
I gave it a try and generally improved the password generator a bit.. (the shown password is limited to 1 line now, but copying it will have the correct length :-) )

![customlength](https://user-images.githubusercontent.com/313066/91832697-02f99b80-ec46-11ea-95c4-8132a8eb5b9a.gif)

what do you think?

**Comment by exalented** [comment]
That is awesome!

**Comment by hpoul** [comment]
This is now already rolling out in 1.7.6
