### ISSUE TITLE
After writing with Authpass, cannot read with KeePassXC

### ISSUE THREAD

**Issue by avuton** [authpass/authpass#134]
After writing to a password file over WebDAV (Nextcloud server, password file kbdx v4) with Authpass from F-Droid on LineageOS, when I try to open the file later in KeePassXC 2.6.1 (Platform: Linux), I get the error  "History element in history entry" and it refuses to open the file anymore. Before this, I got an error "No root group" (I'm sorry, I _think_ that was the error) so I added a quick stub entry in Authpass and saved it to see if it would somehow fix this problem. I'm happy to help test, debug or give any other required information, but I'm at a loss as what to give right now. Looks like Keeweb had a similar issue[1] to which they pointed out [2].

1. https://github.com/keeweb/keeweb/issues/23
2. https://github.com/keepassx/keepassx/blob/master/src/format/KeePass2XmlReader.cpp#L565

**Comment by hpoul** [comment]
Thanks for reporting, I'll have to take a closer look. Sorry for all your troubles.
In the last few days i have been working on file merging/synchronization and with this have fixed quite a few bugs. Have you been able to reproduce this problem with a new file and a single entry? If so it might be worth trying the same with the latest unreleased build. There was a fix where a history entry was cloned from an entry without the `isHistory` flag being set correctly.. 

If you have time, please try the latest sideload apk from https://data.authpass.app/data/artifacts/ - i can also push a new Linux build if that would be easier.

Sorry again, have you been able to repair your file? If not, maybe you could send me the dummy kdbx you created and to make sure new versions of AuthPass can repair it properly

**Comment by avuton** [comment]
No problem at all. From the quick look I took at the other bug report, it seems it could simply be KeePassXC being overly strict about the format and it not actually being broken; thanks for the direction and I'll give it a shot tomorrow.

**Comment by avuton** [comment]
Opened, modified and resaved with sideload 1471 and it now works with KeepassXC as well. Thanks!

**Comment by hpoul** [comment]
Great, thanks for testing :-)

**Comment by avuton** [comment]
This issue is still in F-Droid, despite the release soon after this closed. Is that known?

**Comment by hpoul** [comment]
@avuton thanks for the heads up, but i think fdroid is still on 1.7.5 ... Fdroid is always one or two versions behind, their build process is just annoyingly slow.. they usually build ever two or three days, sometimes it is stuck for a few days https://forum.f-droid.org/t/no-builds-for-4-days/10862 i guess the official recommendation is

> Never hold your breath, please…

😅

And even if the build runs, two out of three times it is broken with network issues, unable to bring up some build_runner, of some other weird error.. https://f-droid.org/wiki/page/design.codeux.authpass.fdroid/lastbuild_145 right now says: "could not bring up vm 'builder_default'"
