### ISSUE TITLE
Password Generator: Improve "Umlauts"

### ISSUE THREAD

**Issue by hpoul** [authpass/authpass#139]
the umlaut class is pretty useless right now:

```
  static const alphabetUmlauts = CharacterString('äüößÄÜÖ');
```

maybe we should extend this to all accented characters. on a first search i couldn't find a package which would already have all accents predefined or something.. but i guess there must be some unicode class or something we could use?

**Comment by RedTahr** [comment]
easiest solution might be to make a list from the characters on the umlauts wiki page and lucene.net github repo to start with.
I've haven't heard of or found a way to programmatically generate accented characters, I was hoping unicode would have a nice table that'd let me get accented characters, but its probably not a normal use case :-)
if there aren't any other takers I could look at this.

**Comment by hpoul** [comment]
@RedTahr thanks for the suggestion, but actually this is already implemented, seems i forgot to close this issue 😅️ I'm basically using all latin1 accent characters. https://github.com/authpass/authpass/commit/d75b7f9a6580f13c0cf8a881737d551e48c469fc#diff-9d470da20f4adc3fe6610addbb21945dR26

basically everything on this page: https://cs.stanford.edu/people/miles/iso8859.html#ISO-UPPER in the tables 'Upper Case Latin-1 Letters' and 'Lower Case Latin-1 Letters'
