### ISSUE TITLE
BUG: Two-finger scrolling doesn't work

### ISSUE THREAD

**Issue by Robio** [authpass/authpass#144]
Two-finger scrolling doesn't work inside an item's Details (I can't speak to the item-list sidebar since I've only created a couple items so far).

I've added two multi-line fields to an item, and between them the content now extends "below the fold." But the only way to get to the content that's below (and the only way to get to the Add Field and Add Attachment buttons) is to click and drag the content up and down.

MacOS 10.13.6 on 2010 MacBook Pro
AuthPass 1.7.7 (1519)

**Comment by hpoul** [comment]
@Robio thanks for the bug report. Unfortunatey I'm unable to reproduce this problem. At least in the current 1.7.8 

textfields expand to fit all text, and I can always scroll the view, even when mouse cursor is above the field, and also when focus is inside the field. Is it still happening i n 1.7.8? Maybe you can provide a screenshot?

<img width="381" alt="Screen Shot 2020-09-19 at 09 35 24" src="https://user-images.githubusercontent.com/313066/93661843-76c7e080-fa5b-11ea-9560-52cba64304a8.png">

**Comment by Robio** [comment]
Hi Herbert,

Sorry, but I've uninstalled.  I like working with software in which I 
see a lot of potential, but I've "over-filled my plate" recently and 
needed to cut some things loose to focus on work. If I wouldn't have to 
re-download and recreate records just to test, I'd have been happy to 
see what happens in 1.7.8.

Cheers,
Rob

Herbert Poul wrote on 2020-09-19 00:36 :

**Comment by hpoul** [comment]
No idea what your are talking any, but thanks for the update.
