### ISSUE TITLE
Wrong icon chosen for evernote.com

### ISSUE THREAD

**Issue by akcoder** [authpass/authpass#146]
AP chooses the image for "The Verge" when I put in the url evernote.com, more specifically this asset: https://evernote.com/c/assets/homepage/the-verge-active.png

The image for "The Verge" is present on the website, but its halfway down the page, and is most certainly not the favicon for the website :)

**Comment by hpoul** [comment]
that's definitely true.. thanks for reporting.. it seems i managed to get the scoring of the images wrong :-) anyway.. i've kind of improved it.. not perfect.. but at least no longer wrong :-)
I think this is still better than the 32x32 favicon.. so I leave it for now this way.. if you find other website icons which are wrong, just create another issue.. if there are too many, i'll might create a collection issue ;-)

<img width="367" alt="Screen Shot 2020-09-18 at 21 25 42" src="https://user-images.githubusercontent.com/313066/93637229-83195280-f9f5-11ea-93a0-1558c4e293b1.png">

**Comment by akcoder** [comment]
How are you getting the site icon right now? One option might be to find the <link rel="manifest" and pull the closest image to the size desired from the icons section. Not all sites use a manifest.json file though...

https://www.yahoo.com/manifest_desktop_us.json

**Comment by hpoul** [comment]
@akcoder evernote's manifest is not really helpful: https://evernote.com/web-app-manifest.json

here are the things i'm looking at: https://github.com/authpass/authpass-cloud/blob/3ae11170cd11b4d057049ecc03778e3b364f4461/packages/authpass_cloud_backend/lib/src/companyimage/besticon.dart#L132-L162

i've now added parsing of structured data:

https://github.com/authpass/authpass-cloud/blob/3ae11170cd11b4d057049ecc03778e3b364f4461/packages/authpass_cloud_backend/lib/src/companyimage/besticon.dart#L352-L362

and I basically chose the ones i think are most likely to be real logos, have a 1:1 ratio, and are closest to 512 pixel wide:

https://github.com/authpass/authpass-cloud/blob/3ae11170cd11b4d057049ecc03778e3b364f4461/packages/authpass_cloud_backend/lib/src/companyimage/besticon.dart#L46-L64

**Comment by akcoder** [comment]
You are right, evernotes manifest is pretty lackluster. Thank you for the clarification. Now to make my sites compliant :).

**Comment by hpoul** [comment]
hmm.. hopefully it's not really required to make sites compliant :-) if no images are found it would still use just the favicon.ico .. and extract the largest image out of it.. if it gets things completely wrong let me know, then I have to improve the algorithm or tweak the scoring.. this is basically still the first try :-)

I've also thought about maybe adding in some form of crowdsourcing, if this isn't working at all :-) we'll see.. imho it's already quite okay :-)

**Comment by hpoul** [comment]
ah and.. right now this thing is *really* dumb.. it caches images *forever* ... i've planned to add some form of regular refetching.. but yeah.. again.. 'good enough' 😅️

**Comment by akcoder** [comment]
Compliant wasn't the right word. More like update my sites so AP automatically picks the icon I want it to :)
