### ISSUE TITLE
Add CONTRIBUTORS.md to about dialog

### ISSUE THREAD

**Issue by hpoul** [authpass/authpass#156]
Should be pretty straight forward.
It would be nice to have the [CONTRIBUTORS.md](https://github.com/authpass/authpass/blob/master/CONTRIBUTORS.md) available in the about dialog inside the app :-)

We could probably symlink it into the authpass/ directory and include it as resource and load it at runtime 🤔️

The only challenge might be rendering the markdown.. in the worst case we could strip it out or something 😅️

**Comment by therealansh** [comment]
hey @hpoul! Can i work on this one?

**Comment by hpnightowl** [comment]
i have added it can i take it?

**Comment by hpoul** [comment]
@therealansh sure, would be awesome ;-) let me know if you need any help or directions, try to keep it simple :-)

**Comment by hpoul** [comment]
@therealansh are you still working on this issue?

**Comment by ATofighi** [comment]
Hi.
I'll work on this issue.
