### ISSUE TITLE
Display a warning to users who use only internal storage

### ISSUE THREAD

**Issue by hpoul** [authpass/authpass#159]
there are too many users without a backup of their password file. We should encourage having a backup.

So until we can sync with our own server #29  we should encourage use of cloud services. Or at least insist on users having a backup.

Ie. if `FileSourceLocal` is used, display a MaterialBanner in the password list with a button which allows the user to save to a cloud storage endpoint.

**Comment by stalkopat** [comment]
I'd like to take a shot at this.

**Comment by hpoul** [comment]
@stalkopat cool :-) sure, everything clear from the description? Let me know if you need any help

**Comment by stalkopat** [comment]
How could we handle people not wanting to backup? 🙂
A dismiss Button could accidentally be clicked and would never appear again. Maybe a setting that allows people to dismiss the warnings would be a possibility, any other suggestions?

There isn't any UI in place to retroactively save a local file to cloud storage thus far right?

**Comment by hpoul** [comment]
@stalkopat I don't think that's too important.. if it's dismissed once, that's enough for now :-)
Well, not 100% what might be required right now but when clicking on the file in the appbar overflow menu a management UI is opened which supports a "Save As":

<img width="308" alt="Screen Shot 2020-09-29 at 13 38 21" src="https://user-images.githubusercontent.com/313066/94553645-1c97fe00-0259-11eb-9b24-349821fdf999.png">

One way would be to refactor this part of the `_ManageFileState` and create something like a `SaveAsWidget` which could be used in a `showModalBottomSheet` in both places? Maybe with a parameter to only show cloud services (ie. without the 'local file' option). What do you think?
