### ISSUE TITLE
Data disappear after click "Unprotect Value"

### ISSUE THREAD

**Issue by KenZync** [authpass/authpass#162]
Data in Field Disappear after click "Unprotect Value"  but it doesn't save so if you go back it's still fine but if save data will be gone

Step to reproduce
1.create entry
2.enter some title
3.protect value and save
4.go back to password list
5.click entry
6.click 3 dots and Unprotect Value
7.data gone

Version 1.7.8+1552

**Comment by hpoul** [comment]
fixed in #172 by @stalkopat 🎉️
