### ISSUE TITLE
Android: Show banner to users to suggest activating autofill

### ISSUE THREAD

**Issue by hpoul** [authpass/authpass#188]
Most users seem to not know that AuthPass on android supports autofill.
At least for Android >= 10 we should probably display a banner in the password list, similar to other banners already implemented if the user has not yet configured AuthPass as password manager.

**Comment by AliAkberAakash** [comment]
Can I work on this issue?

**Comment by hpoul** [comment]
@AliAkberAakash sure

**Comment by tousifalamgir** [comment]
I am also interested in working on this.

**Comment by hpoul** [comment]
@tousifalamgir sure, since there was no pr or anything i guess it is safe to assume nobody is working on it
