### ISSUE TITLE
Fedora 32 x86_64 Linux and Snap: cannot open database.

### ISSUE THREAD

**Issue by AndrewPrzelucki** [authpass/authpass#194]
Installed via Snap, app opens up, settings accessible, but when I select my keepass database and my key file, I get an error message (including screenshot).

My OS is Fedora 32 x86_64. Installed this app from Snap with default "Discover" (preinstalled by Fedora distro) software installation app.

I tried to reopen the same database with KeePassXC and it works, database is fine.
![Screenshot_20201024_171439](https://user-images.githubusercontent.com/61519252/97085504-1f9aca00-161e-11eb-8353-7c8f723af69f.png)

**Comment by hpoul** [comment]
Hi, can you please check the about menu, it should show the path to a log file - maybe you can share this? herbert@authpass.app

**Comment by hpoul** [comment]
seems i forgot to publish 1.7.9 to stable - can you please update and try again? (I assume you were using 1.7.8)

**Comment by AndrewPrzelucki** [comment]
Updated snap and it works now.

**Comment by hpoul** [comment]
Great, thanks for testing :-)
