### ISSUE TITLE
fedora 32 - irritating popup

### ISSUE THREAD

**Issue by marafa** [authpass/authpass#195]
**Describe the bug**

**To Reproduce**
1. new user. so i downloaded the tarbal
2. untarred and ran authpass 
3. this pop up is on every screen i click on. i added a google drive kdbx and must have seen this 4 times.

**Expected behavior**
pop up does not show up

**Screenshots**

![Screenshot_20201024_135519](https://user-images.githubusercontent.com/1518315/97088772-29fa9b00-1601-11eb-9aac-990dae695cba.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] fedora 32 64bit
 - Browser [e.g. chrome, safari] firefox
 - Version [e.g. 22] 32

**Additional context**

**Comment by hpoul** [comment]
do you have gnome keyring installed?

**Comment by marafa** [comment]
Absolutely not
I am a KDE user and used the Fedora KDE live cd to install my OS

**Comment by hpoul** [comment]
do you have ksecretservice installed? or any other implementation of secret service dbus? https://specifications.freedesktop.org/secret-service/latest/

**Comment by marafa** [comment]
kwallet is installed and enabled

**Comment by hpoul** [comment]
unfortunately I have no experience with kwallet - are you sure it implements the `org.freedesktop.secrets.service` d-bus protocol? AuthPass currently uses [libsecret](https://developer.gnome.org/libsecret/) to store authentication tokens for cloud storage to avoid unencrypted storage.
