### ISSUE TITLE
Pressing Ctrl+Shift opens up a browser window.

### ISSUE THREAD

**Issue by aahnik** [authpass/authpass#200]
**Describe the bug**
Pressing Ctrl+Shift opens up a browser window, preventing me from screencasting and screenshotting

**To Reproduce**
1. Go to **authpass app** and open a database
2. Click on **add new password**
3. Press Ctrl + Shift
4. See a browser window popping up. And at the bottom of the authpass app shows `Opened URL:`

I was reporting another bug in authpass and try to screen record using Ubuntu's default `Ctrl+Shift+ALt+R`. But this weird activity of the app is popping up a browser window on the screen.

**Expected behavior**
There were no URLs on the page. URLs should open only when I click an URL. If the app provides any keyboard shortcut, that should be documented and modifiable.

I tried to record this weird activity using the [peek app](https://github.com/phw/peek), but peek's overlay was blocking this weird behavior. After closing peek, the authpass again shows this behavior.

**Desktop:**
 - OS: Ubuntu 20.04

**Comment by hpoul** [comment]
Ah right, i stumbled upon that myself but forgot about it. 😳 Thanks for reporting!

**Comment by hpoul** [comment]
this should be fixed for a while, forgot to close the issue. If this is still a problem please reopen.
