### ISSUE TITLE
Copy & Pasting On Android Authpass ver.1.7.10 

### ISSUE THREAD

**Issue by techcycl3** [authpass/authpass#203]
Hey, was wondering if you knew this bug on your android apk with the copy & pasting for database pass, if you where to copy text from for example a text editor and try and paste it in the /Credentials area to enter your password it will not let you do so.. I've tried testing a few methods to get my database unlocked but to no avail.. This issue did not arise prior to the installation of this app, was working perfectly, now with the new update ver/1.7.10 it has stopped working copy/paste**. I downloaded the app from F-Droid idk if that makes a difference but yeah just kinda worried because I have my accounts on there and need to unlock my database... I've already got the key/pass but I cannot paste. Anyways thanks a lot for this app & your efforts :) -xnocyclic

![Database](https://user-images.githubusercontent.com/53362866/100187181-6d645580-2e9c-11eb-91cf-2111f3abd2e3.jpg)

![Version](https://user-images.githubusercontent.com/53362866/100187189-735a3680-2e9c-11eb-8999-1ebabb8a8980.jpg)

**Comment by hpoul** [comment]
sorry for the late response. Can you please check if this is still happening? This works for me perfectly.
it's possible that there was a broken flutter version. reopen this issue if this is still a problem. thanks
