### ISSUE TITLE
[Translation] Missing translations

### ISSUE THREAD

**Issue by libalis** [authpass/authpass#212]
(Testen on Android 10 with Authpass 1.7.10+1612 and dark mode)
I am using the app in german as it is my system defualt.
Sadly all dialog, e.g. when opening a file or when you have unsaved changes, and the dropdown option "Delete" are not translated.
Would love it if I could help with the translation.
Otherwise, thank you very much for the effort put into this amazing project.
Keep it up.

**Comment by hpoul** [comment]
see #78
