### ISSUE TITLE
[Bug] Can't remove entry from trash

### ISSUE THREAD

**Issue by libalis** [authpass/authpass#213]
(Testen on Android 10 with Authpass 1.7.10+1612 and dark mode)
If I click "Delete" in the drop down menu of an item it gets moved to the "Papierkorb" (Trash).
But I can't delete an entry from the trash, because it sais that I have unsaved changes and discards them.
Even though i clicked save before.
Would be awesome if this bug could be fixed.
Otherwise, thank you very much for the effort put into this amazing project.
Keep it up.

**Comment by hpoul** [comment]
Not sure about the "unsaved changes", but it's just not supported to delete items permanently. see #99 
if there is an additional bug about unsaved changes please reopen and let me know if this can still be reproduced.
