### ISSUE TITLE
custom actions for copying usernames and passwords

### ISSUE THREAD

**Issue by crentava** [authpass/authpass#218]
since auto fill is not implemented on iOS, we have to copy and paste our usernames and passwords from the app to our web browser. I find that going into the password entry, clicking on the menus for the username and password and hitting copy field (At least for us screen reader users) takes a long amount of time. My suggestion is to add custom actions for the password list items that will allow you to copy usernames and passwords. If this can be done I'd be grateful. And just to help. [here is the link to the flutter custom semantics action class](https://api.flutter.dev/flutter/semantics/CustomSemanticsAction-class.html)
thanks for all you've done

**Comment by hpoul** [comment]
That is interesting.. I'll take a closer look. 
Not sure if this is possible when having voiceover activated.. but I'm the password list swiping a password item to the left copies the username, swiping to the right copies the password...
Inside the password details to can actually swipe the field in either direction to copy it, no need for menus.. although as i said, no idea if there is a way to swipe an element with voiceover? 🤔

**Comment by crentava** [comment]
there doesn’t seem to be away as I’ve tried what you said and nothing

**Comment by hpoul** [comment]
Is this a general limitation of voiceover, or only on AuthPass? It's swping a list item working in other apps? Like I'm gmail swping an email in the list for quick archive and snooze?

**Comment by crentava** [comment]
regarding swiping. That’s a general voiceover limitation, what apps such as Gmail do is add custom actions like what I linked you to to make the experience easier for their customers who have either motor disabilities or visual impairments

**Comment by hpoul** [comment]
@crentava I've now tried to add those `CustomSemanticsAction` as i understood them: 

https://github.com/authpass/authpass/commit/0d999673dbab64ff5927c0231af611bf77335694#diff-cb5f1f500be99b3119f43605bd783f0c11ee078497ac0e22eb66cd9021448a4cR1145-R1150

but I have been unable to open them on iOS with voiceover activated... (or without.. or on android.. 🤷‍♂️️) - But i've also tried out the flutter gallery demo and wasn't able to open it either..

What is the gesture to bring it up usually?

I'm pushing a beta version to testflight, it's in review right now and should be available within a few hours. maybe you could give it a try then. Should be coming soon to the TestFlight app. (It's version 1.7.12)

**Comment by crentava** [comment]
custom actions are visible if you swipe down with one finger using voiceover on ios and swiping down then right with one finger on android using talk back

**Comment by hpoul** [comment]
@crentava thanks, now I finally understand what "swipe down" means.. weird, i thought i've tried that before.. but now it's working for me on iOS 🎉️ .. i've added copy username/copy password to the password list.. 
do you think there are any more actions which are missing? 🤔️

**Comment by crentava** [comment]
at the moment I can’t think of any other actions that need to be added. Thanks for all that you’ve done by the way

**Comment by crentava** [comment]
works perfectly. Thanks again
