### ISSUE TITLE
Very low performance on loading and saving (Android)

### ISSUE THREAD

**Issue by danielkochc** [authpass/authpass#219]
**Describe the bug**
If I open a local database on Android it takes ages (about 80 seconds) to load it. It also takes the same amount of time to save a new Entry.

**To Reproduce**
1. Go to main screen. 
2. Click on "open local file"
3. Select the local file to open and enter the password
4. Click continue
5. Wait and wait and wait (about 80 seconds on my phone)
6. Database is opened.

1. Create a new Entry
2. Click on the save button
3. Wait (also about 80 seconds)
4. Entry is saved.

**Expected behavior**
A much faster loading and saving time.

**Smartphone (please complete the following information):**
 - Device: Huawai Mate 20 light
 - OS: Android 10 with latest patches

**Additional context**
The opened database is about 50kb and has only 9 entries.

I guess it could be related to the key transformation iterations of the database, which uses AES-KDF and ~ 20 million iterations (the 1 second delay) on my desktop device.

In a counter test I created a database on the phone and set the iterations to match a one second delay on the desktop in the windows keepass client. Back on the phone the loading time is about 4 to 5 seconds which is quite acceptable and expectable.

**Comment by hpoul** [comment]
Yes, either decrease iteration count, or switch to argon2.

**Comment by hpoul** [comment]
@danielkochc fyi here it's a bit more info: https://github.com/authpass/authpass/issues/58#issuecomment-695258279 i should probably add an faq somewhere. If this doesn't help, let me know.

**Comment by danielkochc** [comment]
Thank you,

The tip to change the key derivation function was flawless. I probably should have tried that myself. I thought it might be a bug, but with your further information I see that it's not really a problem to change the algorithm.
