### ISSUE TITLE
Ubuntu 20.04 (focal) not working due to critical  gdk error

### ISSUE THREAD

**Issue by bltDefender** [authpass/authpass#224]
**Describe the bug**
adding the recommended apt repos then installing authpass as usual. Installation went fine. Registration went fine. Starting authpass results in an empty window. Starting from the console I can read the following warning / errors

`
** (authpass:861030): WARNING **: 19:30:33.567: Failed to start Flutter renderer: Failed to find visual 0x34325241

(authpass:861030): Gdk-CRITICAL **: 19:30:33.567: gdk_window_get_scale_factor: assertion 'GDK_IS_WINDOW (window)' failed
`
The latter repeats many times.
![image](https://user-images.githubusercontent.com/37219611/113031640-3e822700-918f-11eb-9b49-f020f6201cc8.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 focal

**Comment by Farzat07** [comment]
Check #209

**Comment by bltDefender** [comment]
already coverd in #209
