### ISSUE TITLE
i got a problem

### ISSUE THREAD

**Issue by ItzSorin** [authpass/authpass#231]
hi,i got a problem.a long time ago i lost my phone with authpass and the backup code,and i can t login on discord because i don t have the code.can you remove my account from the aps?and after to make a new acconunt with that email?because i really need to connect on discord this week!

**Comment by hpoul** [comment]
No idea what you are talking about. But everything in AuthPass is offline. If you lose it, it's gone. Make a backup.

**Comment by ItzSorin** [comment]
how can i make a backup for my discord? i can t login Sent from my Huawei phone-------- Original message --------From: Herbert Poul ***@***.***>Date: Fri, Jul 9, 2021, 5:16 PMTo: authpass/authpass ***@***.***>Cc: ItzSorin ***@***.***>, Author ***@***.***>Subject: Re: [authpass/authpass] i got a problem (#231)
No idea what you are talking about. But everything in AuthPass is offline. If you lose it, it's gone. Make a backup.

**Comment by hpoul** [comment]
This is the issue tracker for authpass, i have no control over discord.
