### ISSUE TITLE
bug error in reading the fingerprint

### ISSUE THREAD

**Issue by araripi1** [authpass/authpass#234]
[Uploading errobugapp.log.txt…]()
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
[Uploading errobugapp.log.txt…]()
![Screenshot_20210702-060046](https://user-images.githubusercontent.com/76633999/124250822-9ec09600-dafb-11eb-9b1c-9243f9cabc68.png)
![Screenshot_20210702-060033](https://user-images.githubusercontent.com/76633999/124250825-9f592c80-dafb-11eb-86c4-5807d941ef34.png)
![Screenshot_20210702-060024](https://user-images.githubusercontent.com/76633999/124250827-9ff1c300-dafb-11eb-93b0-ea2562c08fa6.png)

**Comment by araripi1** [comment]
> Uploading errobugapp.log.txt…
> **Describe the bug**
> A clear and concise description of what the bug is.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
>     1. Go to '...'
> 
>     2. Click on '....'
> 
>     3. Scroll down to '....'
> 
>     4. See error
> 
> 
> **Expected behavior**
> A clear and concise description of what you expected to happen.
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information):**
> 
>     * OS: [e.g. iOS]
> 
>     * Browser [e.g. chrome, safari]
> 
>     * Version [e.g. 22]
> 
> 
> **Smartphone (please complete the following information):**
> 
>     * Device: [e.g. iPhone6]
> 
>     * OS: [e.g. iOS8.1]
> 
>     * Browser [e.g. stock browser, safari]
> 
>     * Version [e.g. 22]
> 
> 
> **Additional context**
> Add any other context about the problem here.
> Uploading errobugapp.log.txt…
> ![Screenshot_20210702-060046](https://user-images.githubusercontent.com/76633999/124250822-9ec09600-dafb-11eb-9b1c-9243f9cabc68.png)
> ![Screenshot_20210702-060033](https://user-images.githubusercontent.com/76633999/124250825-9f592c80-dafb-11eb-86c4-5807d941ef34.png)
> ![Screenshot_20210702-060024](https://user-images.githubusercontent.com/76633999/124250827-9ff1c300-dafb-11eb-93b0-ea2562c08fa6.png)

**Comment by araripi1** [comment]
![Screenshot_20210702-061130](https://user-images.githubusercontent.com/76633999/124253171-21e2eb80-dafe-11eb-89f8-e8d0bfc682ee.png)

**Comment by hpoul** [comment]
you didn't actually mention what you tried to do, what you happened, what the problem or error message was, etc.
