### ISSUE TITLE
Telegram Support

### ISSUE THREAD

**Issue by mjain234** [authpass/authpass#238]
Is there any telegram support for AuthPass app?

**Comment by hpoul** [comment]
I don't get it, what kind of telegram support are you looking for? (btw, I'd also prefer feature discussions on the [forum](https://forum.authpass.app/c/feature-discussions/7) and keep the issue tracker for actionable tasks)

**Comment by mjain234** [comment]
Like for discussion and other stuffs like any update announcement, and etc

**Comment by hpoul** [comment]
No, there is a forum at https://forum.authpass.app/ and Discord Chat https://discord.gg/Nuraxmc for discussions, and a newsletter for announcements https://authpass.app/docs/newsletter/ .. and the "Releases" page which gets news about all new versions: https://github.com/authpass/authpass/releases - I guess if you really want to, you could use something like https://github.com/pyatyispyatil/github-releases-notify-bot to subscribe to the github releases 🤷‍♂️️

**Comment by hpoul** [comment]
I guess I could try to setup https://meta.discourse.org/t/telegram-notifications-plugin-discourse-telegram-notifications/60483 for the forum, if this helps you. this would kind of integrate the forum into a telegram bot as far as I understand it 🤔️

**Comment by mjain234** [comment]
where does the file kdbx get saved in file manager?
