### ISSUE TITLE
Unable to change to a subgroup on CalyOS

### ISSUE THREAD

**Issue by lfournier** [authpass/authpass#244]
CalyOS on Pixel 4a
Subgroups can be created but only a blank screen shows when trying to change an item's group. Only group that is available is PersonalPasswords

**Comment by hpoul** [comment]
This should be fixed in 1.8.2, which version are you using?

**Comment by lfournier** [comment]
1.8.1 That's the version on fdroid

**Comment by lfournier** [comment]
Aurora Store had 1.8.2 so I uninstalled the version from f-droid  and installed 1.8.2 via Aurora. Works now. Thanks!

**Comment by hpoul** [comment]
Unfortunately fdroid lags behind, and it doesn't sound like they intent to change it any time soon https://forum.f-droid.org/t/update-build-deploy-delays/14191
