### ISSUE TITLE
Allow opening of a kbdx file that have an empty password

### ISSUE THREAD

**Issue by abda11ah** [authpass/authpass#249]
Hello,
I created a kbdx file on keepass that contains hundreds of passwords.
I preferred not to lock the file with a password for simplicity.
Anyway, my bank's websites require double authentication.
Authpass won't open my kbdx file, it requires a password.

**Comment by hpoul** [comment]
I'm a bit surprised that Keepass let's you create an empty master password.. are you using a keyfile instead, or nothing at all?
Would you mind creating a new dummy database when the same configuration as your file? (Maybe with a single dummy entry)? Then I can use that for testing.

**Comment by abda11ah** [comment]
I don't use any keyfile or master password.
This file can be opened in keepassDX app.

https://easyupload.io/4jvnyo

**Comment by hpoul** [comment]
ok, it was enough to basically remove the validator for the password input field, and it opened successfully. I guess supporting opening with empty password can't make anything worse.. but I don't think i'll allow creation with empty password, that seems pretty redundant and more like somebody clicking too fast.

if you want to test it, it should be available in beta versions soonish https://authpass.app/docs/help-us-beta-testing/#installation
