### ISSUE TITLE
Group field is not updated when new entry is generated

### ISSUE THREAD

**Issue by Trekky12** [authpass/authpass#251]
When creating a new password entry and the first action is changing the group (folder) the toast message is shown that the entry is moved, but the field for the group is not updated with the new value.
This behaviour occurs only when the title is empty. If a title is inserted first the group name is updated.

**To Reproduce**
1. Click on "+" button
2. Click on 'group'
3. Select other group
4. See toast message, but value is not updated

The error doesn't occur when this is done:
1. Click on "+" button
2. Insert a value for the title
3. Click on 'group'
4. Select other group
5. See toast message and value is updated

**Expected behavior**
The value of the group is updated.

**Comment by hpoul** [comment]
should be fixed in the latest dev build.

**Comment by Trekky12** [comment]
Hey @hpoul, I noticed that the field is now no longer updated when a title is inserted. Is it possible that this fix broke that?
