### ISSUE TITLE
Save new entry lead to message that there are unsaved changes

### ISSUE THREAD

**Issue by Trekky12** [authpass/authpass#252]
When a new password entry is created a white saving symbol occurs on the top bar.
A click on this symbol results in the saving progress and the symbol gets disabled and is therefore darker. 

During the saving progress it is still possible to click on the arrow back to go back to the list. Unfortunately then the message "There are still unsaved changes" is shown. 
This is only partial correct because the saving is already in progress.

Is it possible to get a better response to the user, e.g.
* disable all buttons until saving is done
* do not show the message when saving is already in progress
* show a message that saving is in progress instead of the warning of unsaved changes
* show a loading animation that saving is in progress

Thank you very much for your effort 👍

**Comment by hpoul** [comment]
that was a bit of a rabbit hole, but I think i've now improved this one.. the way it should work now:

* Once you press "save' you will no longer get the warning about losing changes.
* When the "Save" process fails, the file remains dirty (previously it was always marked as saved, no matter what)
* When you make changes after clicking "Save" but before it is finished, the entry (and file) will remain dirty.

**Comment by Trekky12** [comment]
Thank you very much for your effort. Unfortunately I noticed another inconsistence:
when a new entry is discarded the view changes to the list but the saving icon is still visible.

**Comment by hpoul** [comment]
unfortunately the revert changes is completely broken.. not just for new entries

* #91
