### ISSUE TITLE
Deleting an entry permanently from the recycle bin results in gray window

### ISSUE THREAD

**Issue by Trekky12** [authpass/authpass#253]
When an entry is permanently deleted (from the recycle bin) a gray window is shown. 

**To Reproduce**
1. Go to recycle bin
2. Click on deleted entry
3. Open context menu
4. Click on "Delete Permanently"
5. Click on "Ok"
6. Full screen gray window is shown

**Expected behavior**
After the delete the screen should change to the recycle bin overview.

**Comment by hpoul** [comment]
should be fixed in the latest dev build.
