### ISSUE TITLE
Install attempts from F-Droid are failing

### ISSUE THREAD

**Issue by GlenCooper** [authpass/authpass#257]
**Describe the bug**
When using F-Droid on a mobile phone running GrapheneOS, when you click the "Install" button for AuthPass in F-Droid, it fails with a 404 error.

**To Reproduce**
1. Open F-Droid app
2. Search for "AuthPass"
3. Click "[Install]" button

**Expected behavior**
AuthPass app should install without error

**Screenshots**
![IMG_20210819_111212](https://user-images.githubusercontent.com/967793/130096211-cfe2f3be-f453-4019-9944-b9739deb97ec.jpg)

**Smartphone (please complete the following information):**
 - OS: GrapheneOS
 - F-Droid app v1.12.1
 - Google Pixel 4A with 5G

**Additional context**
Exact 404 failure message: "The requested file was not found.  https://f-droid.org/repo/design.codeux.authpass.fdroid_152.apk"

**Comment by hpoul** [comment]
I don't have much experience with f-droid. But that build looks pretty old, and the website also lists 1.9.1 already https://f-droid.org/en/packages/design.codeux.authpass.fdroid/
Are you sure you have updated the fdroid repo? 🤔

**Comment by GlenCooper** [comment]
> I don't have much experience with f-droid. But that build looks pretty old, and the website also lists 1.9.1 already https://f-droid.org/en/packages/design.codeux.authpass.fdroid/
> Are you sure you have updated the fdroid repo? thinking

Good point.  That's probably it.  It's been a while since I set up this phone.  I'll look into that now and post my findings here soon...

**Comment by GlenCooper** [comment]
Upgraded f-droid from v1.12.1 to 1.13.1.

Tried the install of AuthPass again and now it's downloading it fine without issue.  Thanks @hpoul for the suggestion to update f-droid, it appears that was the solution to my problem.
