### ISSUE TITLE
pub get failed 

### ISSUE THREAD

**Issue by BhavikBolya** [authpass/authpass#265]
[authpass] flutter pub get
Running "flutter pub get" in authpass...                        
Because every version of integration_test from sdk depends on file 6.1.0 and authpass depends on file ^6.1.2, integration_test from sdk is forbidden.

So, because authpass depends on integration_test any from sdk, version solving failed.
pub get failed (1; So, because authpass depends on integration_test any from sdk, version solving failed.)

**Comment by hpoul** [comment]
Did you use the latest Flutter dev release?

https://github.com/authpass/authpass/blob/9fa32542a9a1678ff9f220f78f6ad26737fc2fa7/authpass/_tools/_flutter_version_update.dart#L15
