### ISSUE TITLE
Scaffold for windows desktop app

### ISSUE THREAD

**Issue by hpoul** [authpass/authpass#27]
https://docs.microsoft.com/en-us/windows/win32/api/wincred/nf-wincred-credwritea?redirectedfrom=MSDN

**Comment by TobiasDev** [comment]
Are there any updates on the status of a windows and/or Linux build? From the Flutter team.

**Comment by hpoul** [comment]
@TobiasDev you can watch the flutter team's progress at https://github.com/flutter/flutter/projects/37 (windows) and https://github.com/flutter/flutter/projects/38 (linux) ... my feeling is.. it's progressing pretty rapidly.. the main blocker is still, that there is no actual "release" mode .. i think the linux side is a bit further along https://github.com/flutter/flutter/issues/38478 .. and tooling for plugins is still not "final" so it's still discouraged to actually publish windows/linux plugins.. 

but from the looks of it it would already be possible/feasible to add support for it, the basic version would be more or less just using the master channel with:

```
flutter config --enable-windows-desktop
flutter create .
```
https://github.com/flutter/flutter/wiki/Desktop-shells#tooling this should get at least the start screen running :-) then there are only a handful of plugins which are *really* required.. (file picker, url_launcher ([which afaik already has ports](https://github.com/google/flutter-desktop-embedding/tree/master/plugins/flutter_plugins/url_launcher_fde))) everything else are basically nice to haves.. (like share, email sender, biometric storage for quick unlock, ..)

i'm already pretty tempted to try it out, but i'm still waiting a bit on the release mode.. and since i only own a mac, i'm still a bit hesitant getting a VM configured for linux.. and i'll probably pass on windows altogether until there is some demand..

**Comment by hpoul** [comment]
@TobiasDev the release modes for windows and linux have now been merged into flutter master. I have given linux a try, and it seems to work pretty good.. Basic features are already working (opening files, kdbx 4 with argon 2, etc.). Are you using both windows and linux?

Unfortunately I don't own a PC (or windows license) but only macs.. I'm pretty sure windows should not be more difficult than linux.. 

btw, if anyone has linux and want to try it out, i've uploaded a first version to the linux issue: https://github.com/authpass/authpass/issues/26#issuecomment-637606572

**Comment by TobiasDev** [comment]
Oh, cool! Yeah, I'm sadly on Windows and Linux (would love to leave Windows but need it for work). I will give Linux a try asap, though for me personally to be able to switch I would need the KeePassXC browser plugin API to work with AuthPass. :) Since I use that daily.

If you want I can also look into compiling a Windows version beginning of next week. :)

**Comment by hpoul** [comment]
I've looked at the browser plugins, but the protocol(s) looks pretty complicated to implement, with many moving parts. It's not like there exists a generic API to be implemented, rather a couple of browser plugins for specific keepass apps. So I don't think I can focus on that right now.. but if somebody ever wants to give it a try, i'm happy to help out ;)

thanks, let me know how it goes, no hurry :)

**Comment by hpoul** [comment]
I have now created a very early version, maybe someone can give it a try? (@TobiasDev maybe? :) ) It has still no support for cloud storage (google drive, dropbox, webdav) and no support for argon2 (kdbx 4). But it would be helpful if anyone could try that it actually launches ;-)

[authpass-windows.zip](https://github.com/authpass/authpass/files/4911973/authpass-windows.zip)

**Comment by hpoul** [comment]
here is an updated installer.. it still misses cloud storage support, but other than that i think it's pretty much working: https://data.authpass.app/data/artifacts/AuthPassSetup-1.6.5_1298.exe

**Comment by TobiasDev** [comment]
Sorry! I was super busy the last two months. :( But I will open it up today and have a look! Though I won't be able to open my file unless it supports KDBX4 since I have that format. :)

**Comment by hpoul** [comment]
@TobiasDev the latest version should support kdbx 4 now. :) although I haven't tried it yet 😅️ let me know how it went. (still no cloud storage support.. but this shouldn't be too much work as well, the only requirement is to have a secure storage for the cloud storage auth tokens which boils down to implementing https://github.com/timsneath/win32/issues/70 :) )

**Comment by TobiasDev** [comment]
> 
> 
> @TobiasDev the latest version should support kdbx 4 now. :) although I haven't tried it yet 😅️ let me know how it went. (still no cloud storage support.. but this shouldn't be too much work as well, the only requirement is to have a secure storage for the cloud storage auth tokens which boils down to implementing [timsneath/win32#70](https://github.com/timsneath/win32/issues/70) :) )

Yeah, I understand that! Though for the Desktop version cloud-storage isn't that high prio for me personally. :) I keep my NextCloud folders all synced to my computer so I can always just open the file directly on my Windows PC (at least as long as I'm working from home). :D When I'm back at work it might be harder since then I can't install NextCloud.

**Comment by TobiasDev** [comment]
Just installed it and tried opening my file, but got this: 
![grafik](https://user-images.githubusercontent.com/5912371/87522907-81927d80-c686-11ea-89a4-baf4c3ae0f88.png)

**Comment by hpoul** [comment]
@TobiasDev thanks for testing, although i'm already impressed that the installer worked and you actually saw an error message 🎉️ .. I've made a few fixes, maybe you can give this one a try: https://data.authpass.app/data/artifacts/AuthPass-setup-1.6.5_1307.exe

**Comment by TobiasDev** [comment]
Okay! Sorry for not letting you know instantly, but I have now tried the app for two days! Everything seems to work! I haven't run into any issue and I can do all the things I except to do. :)

**Comment by hpoul** [comment]
@TobiasDev sounds great, thanks :-) i'm just adding winsparkle (auto-updater) and credential store (for cloud storage) .. then the windows version should be pretty much done 🎉️

btw. how do windows users nowadays discover apps? :-) since there is no app store (or at least i *think* windows store is only for UWP, not for win32?)

**Comment by TobiasDev** [comment]
Good question. I usually use [Chocolatey](https://chocolatey.org/packages) or simple look at the website. I hate the UWP (personal opionon though), so I never ever look there and usually end up looking for alternatives if that is the only place to get the app. :P

**Comment by hpoul** [comment]
Since windows is now released, auto update seems to work, i'm closing this issue :-) let me know if there are any further problems on windows. (since i don't use it regularly myself it's always good to get feedback whether anything is still working 😅️)

I've created a new issue for creating a Chocolatey bundle https://github.com/authpass/authpass/issues/117 - I'm not sure if it's really *that* useful but maybe it improves discoverability.
