### ISSUE TITLE
Linux distribution: Create debian package (.deb) (for ubuntu and debian)

### ISSUE THREAD

**Issue by hpoul** [authpass/authpass#272]
I previously tried to build `ppa` packages for ubuntu at https://github.com/authpass/authpass-deb but I don't think this works anymore.
It would be nice to make AuthPass available as deb packages. Maybe using a custom repository on `https://data.authpass.app`.

This issue is for creating a github workflow which builds a debian package and maybe a directory archive or hierarchy which can be rsync'd to a debian repository.

**Comment by Atharva321** [comment]
Hii, I am interetsed to work on this issue.
What steps should I follow?
I am a beginner.

**Comment by hpoul** [comment]
> What steps should I follow

@Atharva321 beginner in what exactly? First understand how to build Debian packages.. then turn the`tar.gz` into an installable Debian packages.. then see how to host a deb package repository.. afterwards integrate everything into a github actions workflow..

If you are a beginner in all of this, it will probably take quite some effort. And since I'm no Linux user and have no experience with deb packages myself (except building the current build system, which is broken) i won't be able to help out too much. A good understanding of Linux/Debian would probably be helpful.

**Comment by Atharva321** [comment]
I want to give it a try.

**Comment by hpoul** [comment]
@Atharva321 👍️ awesome.. let me know if I can help you with anything.. I guess it would be the easiest to take the built `.tar.gz` and just package it up.. https://authpass-data.codeux.design/data/artifacts/authpass-linux-latest.tar.gz .. the last time I played around with the dependencies I came up with where https://github.com/authpass/authpass-deb/blob/master/substvars
the nicest thing I guess would be something like a shell script which can be called in a github workflow which creates a `deb` package as well as a package repository to rsync to some static web server.

**Comment by GameTec-live** [comment]
> Debian packaging is complex and you really need a solid understanding of the Debian ecosystem to package anything.

dont rly think so, even tho for advanced packages this is needed...

**Comment by GameTec-live** [comment]
@hpoul i could give it a try to create a actions workflow, as soon as i find time...

**Comment by GameTec-live** [comment]
i think i have a data structure, that could work...
<img width="494" alt="image" src="https://user-images.githubusercontent.com/66077766/175022962-2123d697-da53-4b22-b463-bce6f2dcbcdd.png">

**Comment by GameTec-live** [comment]
[authpass.zip](https://github.com/authpass/authpass/files/8958153/authpass.zip)
i think ive got to throw in the towel for now, it builds and if you run /opt/authpass it works, but im rn failing at the symlink postinstall script part.... maybe ill come back later

**Comment by GameTec-live** [comment]
i got it to build without errors! @hpoul 
now ive just got to make it into a actions flow and do some finetweakin
[authpass.zip](https://github.com/authpass/authpass/files/8967179/authpass.zip)
g

**Comment by GameTec-live** [comment]
would it be possible to include a svg version of the logo in the source?

**Comment by GameTec-live** [comment]
and for completeness, here is the tree... 
<img width="432" alt="image" src="https://user-images.githubusercontent.com/66077766/175304494-1313e36a-b076-48e3-ba58-88a2dae6824e.png">
ima continue tomorrow, where hopefully a svg icon is included

**Comment by GameTec-live** [comment]
Got it! pr #310 open!

**Comment by hpoul** [comment]
Okay perfect, thanks to @GameTec-live there is now a debian package.. 🥳
