### ISSUE TITLE
Many Suggestions & Feedback for AuthPass

### ISSUE THREAD

**Issue by the-code-creator** [authpass/authpass#295]
## **Many Suggestions & Feedback for AuthPass**

**Hello guys**,
I've been searching for an open source, offline password manager and ended up with **AuthPass**, because it's available on all major platforms **including iOS** which is unique.👍

I have some suggestions & feedback for AuthPass that I'd like to share:

### **Features to be added in the settings:**

* Autosave option

* Clipboard auto-clear after X seconds

* CSV export & import

* When you disable screenshots of the app, this should also apply to the password list
(currently only disabled when an entry is viewed)

* iOS: Add disable screenshots option

* Show the AutoFill option. When you click on it, a short description will be displayed. At the bottom, a button will redirect users to the device settings so they can enable AutoFill

---
### **User interface suggestions:**

* Password generator: Be able to deselect/exclude look alike characters

* Password generator: Be able to select a custom list of characters to be included
(use case: User only wants specific special characters included in the PW)

* Only create an entry after you hit the save-button
(to avoid empty entries from being added by mistake)

* When you have a group selected in the filter and you press the + button to add a new entry, the filtered group will automatically be inputted in the entry, which is very useful, but this doesn't happen when you instead press the "Add new Password" button 
Suggestion: "Add new Password" button should add the filtered group too like the + button

* Be able to select multiple entries at once and then be able to click a delete button
(instead of having to click on every entry one by one, click the dots-menu and only then being able to click the delete button)

* Save the selected filters and don't clear them after closing the app/database
(every time you open a database, the last used filters will be applied - just like the password-generator preferences are saved)

* Be able to manually sort the groups by dragging them
(the order is saved like the password-generator preferences)

* Add collapse/expand buttons next to the group names
(so the menu is tidier if you got lots of groups - eg I don't need all the groups in the trash visible)

---
#### **General**

* Add AutoFill for iOS

* Add Auto-Type for Windows & Linux like with KeePass

* After pressing the AutoFill button and unlocking the database, the URL in the search bar will include "www.". Please remove that, because most people don't safe the URLs with "www." included.

#### **Android**

* After selecting an entry, you have to press another button again so that the fields are filled. This unnecessary extra step should be removed.

* Issue: The AutoFill button often appears but then disappears quickly and you have to select the input fields multiple times, so that it stays...

---
### **Other suggestions:**

* Publish browser extensions (first for Chrome & Firefox) for automatic form-fill

##
* This might be hard to implement but I'll suggest it anyways: Option to connect your other devices that have AuthPass installed and enable automatic **local WiFi synchronisation**

So I'm currently using [Syncthing](https://syncthing.net/) which is an open-source program/app to synchronise files from your phone/computer to your other devices via local WIFI without any cloud involved.

Syncthing doesn't have an official iOS app, but I'm using the app "[Möbius Sync](https://apps.apple.com/us/app/mobiussync/id1539203216)" (also open-source) which incorporates Syncthing.

I have my iPad, Android Phone and Computer connected and my database is automatically synchronised between all my devices - no cloud provider needed!😄👍

Of course it would be easier if AuthPass implemented local WiFi synchronisation. A password manager already having this feature is [StickyPassword](https://www.stickypassword.com/synchronization-and-backup) (not open-source).

This feature would set AuthPass apart from all other password managers - being open-source **AND** supporting WiFi synchronisation!😮

##
**Thanks for reading my suggestions & feedback - if you got any questions, feel free to ask and have a nice day!😃**

**Comment by hpoul** [comment]
Hello,
thanks for all your feedback. unfortunately i'm pretty busy atm with other things. And I think it would be better to split up each suggestion and discuss it in a separate thread in the forum suggestions.. But honestly, until somebody would be interested to contribute code, the chances are that I won't be able to implement everything on my own 😂 I'm also pretty much limited to MacOS and Android, since those are my daily drivers.. I won't invest heavily in windows/linux/ios, since i'm not using it at all.

p.s. I've now seen that you posted in the forum as well, so i'll close it here.

**Comment by the-code-creator** [comment]
@hpoul Maybe other people here on GitHub would like to comment on my suggestions, so please leave it open.😄
