### ISSUE TITLE
Decrypt with keyfile

### ISSUE THREAD

**Issue by hpoul** [authpass/authpass#3]

**Comment by bigbear3001** [comment]
Would be great to have this.

**Comment by hpoul** [comment]
@bigbear3001  will look into this, should be quite easy.. it's just prepended to the hashed password iirc :) I just didn't implement it yet because i didn't think anyone would actually use it.. it's quite cumbersome to share keyfiles with mobile devices.. :)

**Comment by hpoul** [comment]
@bigbear3001 fyi, i've now basically implemented keyfile support.. ( https://github.com/authpass/authpass/commit/10d4856cfcd68f87d6e28edfea04d16f5be7a890 ) just needs a bit more testing with different combinations.. (password + keyfile, only keyfile, android, ios, macos, etc.) :)

**Comment by hpoul** [comment]
decryption with keyfile is now implemented. Here is a prerelease . version if you've got time to try it:
 [AuthPass.app-mac-1.3.0.zip](https://github.com/authpass/authpass/files/3762024/AuthPass.app-mac-1.3.0.zip)

for a full release i've got a few more things on my todo list in the next few days (hopefully)

**Comment by bigbear3001** [comment]
I tested it and it works with a newly generated test database. Unfortunately it does not work with my database. I could not yet figure out what the difference between the files is. All the settings seem to be the same.

**Comment by hpoul** [comment]
@bigbear3001 thx for testing.. what is the error message? Is it invalid password or something else? (That should be the difference between error during decryption and error while parsing xml) .. have you checked if it is kdbx 3 (but 4) - I'm not sure how to check that in keepass though, I've never actually used it directly ;)

**Comment by hpoul** [comment]
@bigbear3001 nvm re error message.. missed the last sentence :) that one did not make it into the email notification ;)

**Comment by hpoul** [comment]
@bigbear3001 this is a bit weird, because kdbx 4 should give you another error message.. maybe you could take a look at `~/Library/Containers/design.codeux.authpass/Data/Library/Application Support/design.codeux.authpass/logs/app.log` if there are any more hints.

**Comment by hpoul** [comment]
keyfile should be working, i've also improved error messages when encountering kdbx 4 files. closing issue.

**Comment by bigbear3001** [comment]
i just downloaded 1.4.1 from the App Store (it still says 1.0.0+1 in the about dialog of the app)

it's not working, it says invalid password. in the logfile the messages are:
```
2020-02-11 20:50:27.072086 WARNING kdbx.format - Unable to parse key file as hex or XML, use as is."<" expected at 1:1#0      parse (package:xml/xml.dart:80)
#1      new KeyFileCredentials (package:kdbx/src/kdbx_format.dart:71)
#2      new Credentials.composite (package:kdbx/src/kdbx_format.dart:31)
#3      _CredentialsScreenState._tryUnlock (package:authpass/ui/screens/select_file_screen.dart:718)
<asynchronous suspension>

2020-02-11 20:50:27.078447 FINER kdbx_bloc - Reading from secure  bookmark. (File: '/Users/bigbear3001/ownCloud/KeePass/Database.kdbx')
2020-02-11 20:50:27.078625 WARNING kdbx_bloc - Stored secure bookmark resolves to a different file than we originally opened. File: '/Users/bigbear3001/ownCloud/KeePass/Database.kdbx' vs. File: '/Users/bigbear3001/ownCloud/KeePass/Database.kdbx'
2020-02-11 20:50:27.079043 FINE kdbx_bloc - startAccessingSecurityScopedResource: true
2020-02-11 20:50:27.140710 FINE authpass.select_file_screen - Invalid credentials. (PlainTextPassword)Instance of 'KdbxInvalidKeyException'#0      KdbxBloc.openFile (package:authpass/bloc/kdbx_bloc.dart:444)
<asynchronous suspension>
#1      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:75)
<asynchronous suspension>

2020-02-11 20:50:40.667079 WARNING kdbx.format - Unable to parse key file as hex or XML, use as is."<" expected at 1:1#0      parse (package:xml/xml.dart:80)
#1      new KeyFileCredentials (package:kdbx/src/kdbx_format.dart:71)
#2      new Credentials.composite (package:kdbx/src/kdbx_format.dart:31)
#3      _CredentialsScreenState._tryUnlock (package:authpass/ui/screens/select_file_screen.dart:718)
<asynchronous suspension>

2020-02-11 20:50:40.721306 FINE authpass.select_file_screen - Invalid credentials. (PlainTextPassword)Instance of 'KdbxInvalidKeyException'#0      KdbxBloc.openFile (package:authpass/bloc/kdbx_bloc.dart:444)
<asynchronous suspension>
#1      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:75)
<asynchronous suspension>
```
PlainTextPassword was my password (so if possible please don't log that in the future)

**Comment by hpoul** [comment]
thanks for the log.. sorry for the plain text password, fixed that in the [next version](https://github.com/authpass/authpass/commit/de048b9e72fca7ad05c0f5ed14a69e4033035619) . (Also fixed displaying of version number on macos). but to the actual problem.. :-) how have you created the keyfile? Using KeePass? Could you maybe create me a new dummy database file with keyfile so I can test it.. Because the one I've created worked for me (™) although i have used Keeweb iirc. https://github.com/authpass/kdbx.dart/blob/master/test/password-and-keyfile.key

**Comment by hpoul** [comment]
@bigbear3001 any chance you can send me a test file? ;-) also, I have now added ("experimental" - ie. it works for me) support for kdbx 4.x.. if you've got time, maybe you could give it a try.. (version 1.5.0 .. i'll release it soon'ish)

[AuthPass.app-1-5-0-b122.zip](https://github.com/authpass/authpass/files/4257922/AuthPass.app-1-5-0-b122.zip)

**Comment by bigbear3001** [comment]
@hpoul i think i created the keyfile with keypass 1.x (i later migrated the db to keepass 2.x .kdbx), it looks like a 64 characters long hexstring.

I created a new test database like my current one (although the new one was created with keepass 2.x and the hex key generated on bash from /dev/random), password is testing99
[NewDatabase.zip](https://github.com/authpass/authpass/files/4258280/NewDatabase.zip)

**Comment by hpoul** [comment]
@bigbear3001 thanks for the file.. but that database seems to work? so there is only a problem with your main database file which isn't (easily) reproducible with a new database?

**Comment by bigbear3001** [comment]
Ok i think i figured it out. My original keyfile (the one that doesn't work) is missing the newline at the end. I attached another sample database with a keyfile that is not working. (password is testing99 again) 
[NewDatabase2.zip](https://github.com/authpass/authpass/files/4289095/NewDatabase2.zip)

**Comment by hpoul** [comment]
@bigbear3001 cool, thanks.. that's an easy fix :-) if you've got time, maybe you could give this release a try: 
[AuthPass.app-1-5-1-b123.zip](https://github.com/authpass/authpass/files/4294851/AuthPass.app-1-5-1-b123.zip) thanks!

**Comment by bigbear3001** [comment]
yes with 1.5.1+123 my original database also works, thanks

**Comment by hpoul** [comment]
i'm pretty confident that all combinations should work right now.. binary keyfile, base64 keyfile with newline, without and XML. in the latest (1.5.1/1.5.2) also supports kdbx 4.x with basically any combination of encryption settings (argon2, aes-kdf, chacha20, aes encryption) - so will be closing this issue for now 🙏️
