### ISSUE TITLE
Android Auto-Fill for password forms

### ISSUE THREAD

**Issue by hpoul** [authpass/authpass#30]

**Comment by hpoul** [comment]
first version done in 1.2. Still a bit experimental, but working.

**Comment by BeneCollyridam** [comment]
@hpoul
I have not been able to get this to work. I get a popup saying "Autofill with AuthPass" but when I press it nothing happens.

**Comment by hpoul** [comment]
@BeneCollyridam well to be honest this is still a bit clunky at times.. this is how it should work: 

1. click on the 'Autofill with AuthPass'
2. Unlock your kdbx database
3. Select the desired entry - this will finish the activity and push you back into the previous activity
4. instead of 'Autofill with AuthPass' you see the title of the selected entry.. when selecting it, it should auto fill username/password.

![Screen_Recording_20200319-142108 2020-03-19 14_28_16](https://user-images.githubusercontent.com/313066/77072389-e518e100-69ed-11ea-8f0c-d2a782b779ad.gif)

(yep, there are also quite a few dark mode issues still)

**Comment by BeneCollyridam** [comment]
This is what I get, when I try to log into Reddit
![screen](https://user-images.githubusercontent.com/15802915/77073947-55c0fd00-69f0-11ea-84fd-65b3011422d7.gif)

**Comment by hpoul** [comment]
@BeneCollyridam that's weird.. can't reproduce this with reddit.. is it the same behaviour for all apps? what android version/device are you using?

**Comment by BeneCollyridam** [comment]
Yes, it is the same for all apps. It works correctly with Lastpass, which I used to use. 

Phone:
Model: Xiaomi Mi 9T
Rom version: MIUI Global 11.0.4
Android version: 10 QKQ1.190825.002

**Comment by hpoul** [comment]
@BeneCollyridam i've got a theory, can you try to open AuthPass directly.. and then force close/stop it through the application settings and try the autofill again.. it looks a bit like this flutter bug: https://github.com/flutter/engine/pull/16916

**Comment by Nadyita** [comment]
I'm on the latest MIUI 12.0.2 on a Pocophone F1 and experiencing the exact same behaviour: if I click the autofill, nothing happens. Forcefully closing/stopping it doesn't change anything.

**Comment by hpoul** [comment]
@Nadyita in which apps did you try it? do you by chance have the possibility to attach it to a PC with android dev tools to see if there is anything in the log files?

**Comment by Nadyita** [comment]
@hpoul It happens with both, Firefox and Chrome. I'm sure I can attach it, just tell me how to get the logs

**Comment by gryphonmyers** [comment]
I get this exact problem as well on my new Poco X3 NFC. It worked great on my old Motorola phone. There is a clear pattern here - everyone in this thread suffering from this problem is using Xiaomi MIUI. There must be some customization they put in place that breaks authpass' autofill. @hpoul I am happy to provide any assistance debugging this issue. Really missing autofill on this phone

**Comment by gryphonmyers** [comment]
Actually, I figured out the cause and workaround! Go into Settings -> Apps -> Manage Apps -> Authpass -> Other Permissions -> Display pop-up windows while running in the background. Enable this. Autofill should work now
