### ISSUE TITLE
[RFE] upon opening entry present user with fields in view-only mode and button to enter edit mode

### ISSUE THREAD

**Issue by hgkamath** [authpass/authpass#304]
this was suggested in issue #303 

Feature request 

### Description
Upon opening pre-existing entry from 'entry-list' activity-window, first take user to a 'view-only-mode' activity window. In this 'view-only-mode' window, the user should be able to view values of fields in non-edit-able view-only-label-fields and hence, should not be able to edit. An 'edit' button this 'view-only mode' activity window should then take user to the usual 'edit-mode' activity-window in order to edit/make changes. This usual 'edit-mode' activity-window then already has values in edit-able text-fields that can be modified as well as the 'back' and 'save' buttons. In most cases, the user is only wants to view fields. Only when the user wants to edit fields, should the user have to press the 'edit' button in the 'view-only-mode' activity-window to goto the edit-mode, where user can make changes, save changes and exit edit-mode in order to return to 'view-only-mode'. Another advantage of the 'view-only mode' is that the android keyboard won't keep popping up, while just reading-off or copying-off field-values.
This is a good feature to have even after fixing #303. and if fixed before fixing it, it definitely reduces the chance of encountering it as well as protects from other inadvertent user errors.

### Current situation
Presently, upon opening entry from the 'entry-list' activity-window, the user is directly taken to an 'edit-mode' activity-window with edit-able fields. It is possible to inadvertently clobber previously entered values in the fields.

**Comment by hpoul** [comment]
see 
* #148
* #107
