### ISSUE TITLE
Win10 Indicates that a virus exists.

### ISSUE THREAD

**Issue by Dboy233** [authpass/authpass#307]
Win10 Indicates that a virus exists.
 
![image](https://user-images.githubusercontent.com/37604230/173712015-0f3b6d0e-b18a-4786-91f5-1d4f637ebd6a.png)

**Comment by hpoul** [comment]
🤷‍♂️ can't fix the windows virus scanner.. from what i see everything seems clean https://virusscan.jotti.org/en-US/filescanjob/ujelaq7lef
