### ISSUE TITLE
[Item request] SVG version of the logo included in source

### ISSUE THREAD

**Issue by GameTec-live** [authpass/authpass#309]
This issue is related to #272. Id like to have a SVG version of the logo somewhere in the source. (PLS somewhere in the data folder!)

**Comment by hpoul** [comment]
well, if you mean the bare bones logo for the launch icon, it's actually already in the repository twice:

* https://github.com/authpass/authpass/blob/main/_docs/authpass-logo.svg
* https://github.com/authpass/authpass/blob/main/authpass/ios/Runner/AuthPassMacLogo.svg

why do you need it? Which data directory? feel free to copy it to another location.. but I prefer if it when it would only end up in the linux distribution.. not in every release bundle.. (ie. not in the assets folder).

**Comment by GameTec-live** [comment]
https://github.com/authpass/authpass/blob/main/_docs/authpass-logo.svg and this is the logo i meant... (including it in the tarball would make stuff easier!)

**Comment by GameTec-live** [comment]
i found a pretty easy way to do that with actions, so if you dont want to, its ok...
