### ISSUE TITLE
Authorization link provided during OneDrive login not working

### ISSUE THREAD

**Issue by jotbeh** [authpass/authpass#318]
Hello everybody,

for about a week now, Authpass has prompted me to reauthorize its OneDrive access, as the granted token has expired.

However, when I try to log out of OD and then log in again, the provided authorization link (https://login.microsoftonline.com/common/oauth2/v2.0/authorize ... ) returns an "Address Not Found" error in the browser.

Did OneDrive perhaps change its authorization method?

Thank you in advance!

**Comment by hpoul** [comment]
strange, everything works for me. Which version/platform of AuthPass are you using? Can you take a screenshot of the error message.

**Comment by jotbeh** [comment]
I'm using the Android version: 1.9.6+1904.
The error message is the browser's usual "Address not found". I'm not redirected to a login page to put in my credentials.
![Screenshot_20220629-144906_Fennec](https://user-images.githubusercontent.com/27549997/176440427-bcb5b776-dbd1-4bd5-84f2-8b640ae1d26f.png)

**Comment by hpoul** [comment]
This looks more like it can't resolve the host name, and not that the login is wrong. What happens when you open that url:

https://login.microsoftonline.com/ .. if this is working.. can you paste the full URL? I also don't understand why the address bar shows indicates an insecure page.. since it's definitely `https`.

**Comment by jotbeh** [comment]
You're right, that _is_ strange. For some reason https://login.microsoftonline.com/ also isn't resolved. I tried disablingpprprivate DNS and ad-blocking addons, but no dice.
Seems to be an error specific to my device/setup.
