### ISSUE TITLE
Microsoft Store App Does Not Load

### ISSUE THREAD

**Issue by Turux** [authpass/authpass#319]
Authpass just loads a blank screen

**To Reproduce**
Steps to reproduce the behaviour:
1. Open Authpass 1.9.7.0 installed from the Microsoft Store

**Desktop (please complete the following information):**
 - OS: Windows 10 21H2
 - Authpass Version 1.9.7.0

**Comment by hpoul** [comment]
can you check the windows event viewer if you find any error messages?

could you try an old version if that works for you: https://data.authpass.app/data/artifacts/AuthPass-setup-1.9.6_1908.exe

**Comment by Turux** [comment]
Hi @hpoul,

No errors in the event viewer (I'm looking at the Application log, anywhere else I should check?)
Also, the normal executable works perfectly fine even with the latest version (1.9.7+1940). 
This seems to be an issue exclusively with the Microsoft Store app

**Comment by nitishpatel** [comment]
> Authpass just loads a blank screen
> 
> **To Reproduce** Steps to reproduce the behaviour:
> 
> 1. Open Authpass 1.9.7.0 installed from the Microsoft Store
> 2. See error
> 
> **Desktop (please complete the following information):**
> 
> * OS: Windows 10 21H2
> * Authpass Version 1.9.7.0

Facing Similar Issues
![image](https://user-images.githubusercontent.com/39486276/177199210-b0d5e82f-718c-43a8-a374-e5dd98ba113d.png)

**Comment by hpoul** [comment]
It was now accepted in the microsoft store. Let me know if you still experience problems. Thanks
