### ISSUE TITLE
Disabling screenshot function on Android v1.9.7 has a bug

### ISSUE THREAD

**Issue by Silverhawk85** [authpass/authpass#320]
The disable screenshot function in the android app seems to have a bug.

1. Disable screenshot function in the settings (at this time it works)
2. Close the app
3. Reopen AuthPass
4. Take screeshots although the function seems to be disabled in the settings

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A6 plus
 - OS: Android 10

**Comment by Silverhawk85** [comment]
> Thanks for the report. It should be fixed now in the latest beta. You can opt in for the beta at https://play.google.com/apps/testing/design.codeux.authpass


I use F-Droid or direct apk download on GitHub. But thanks for the fast response. I have to wait for the full release. :)

**Comment by hpoul** [comment]
@Silverhawk85 you can download the apks for all builds at https://data.authpass.app/data/artifacts/ so for example https://data.authpass.app/data/artifacts/authpass-sideload-1.9.9_1945.apk

**Comment by Silverhawk85** [comment]
> @Silverhawk85 you can download the apks for all builds at https://data.authpass.app/data/artifacts/ so for example https://data.authpass.app/data/artifacts/authpass-sideload-1.9.9_1945.apk

Thanks I downloaded it. The bug seems to be fixed. :)
