### ISSUE TITLE
Authpass won't update (using apt)

### ISSUE THREAD

**Issue by TheRealPenguin12** [authpass/authpass#322]
**Describe the bug**
When I update my system it returns:

```
Err:5 https://packagecloud.io/authpass/authpass/raspbian bullseye Release
  404  Not Found [IP: 52.52.144.96 443]
```

**To Reproduce**
1. Go to shell
2. Run sudo apt update
3. Wait for error

**Expected behavior**
The command will output:

```
Err:5 https://packagecloud.io/authpass/authpass/raspbian bullseye Release
  404  Not Found [IP: 52.52.144.96 443]
```

**Screenshots**
_No screenshot available_

**Desktop (please complete the following information):**
 - OS: Raspberry Pi OS, 32-bit
 - Browser: Chrome
 - Version: 1.9.7

**Additional context**
_No additional context available_

(It might just not work very well with my computer)

**Comment by hlgrondijs** [comment]
I'm getting a similar 404 Not Found error for the `https://packagecloud.io/authpass/authpass/ubuntu` url as well.

**Comment by desvasicek** [comment]
So for ubuntu too, I guess

**Comment by TheRealPenguin12** [comment]
I reinstalled.
