### ISSUE TITLE
Authpass for deb file does not install properly

### ISSUE THREAD

**Issue by dtantono** [authpass/authpass#325]
**Describe the bug**
missing dependency

**To Reproduce**
1. type sudo dpkg -i authpass-linux-1.9.7_1940.deb
2. I got error Preparing to unpack authpass-linux-1.9.7_1940.deb ...
Unpacking authpass (1.9.7+1940) ...
dpkg: dependency problems prevent configuration of authpass:
 authpass depends on libsecret-1-0 (>= 1.15.0); however:
  Version of libsecret-1-0:amd64 on system is 0.20.4-0ubuntu1.

**Expected behavior**
it should install properly

**Screenshots**
![image](https://user-images.githubusercontent.com/29157187/184559824-73617af6-5df7-44eb-97b4-b5ba434923e2.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Version 1.9.7

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hpoul** [comment]
guess i should do another release..
please try: https://data.authpass.app/data/artifacts/authpass-linux-1.9.9_1945.deb
