### ISSUE TITLE
Is the project still active? 

### ISSUE THREAD

**Issue by ashutoshsaboo** [authpass/authpass#329]
Hi, first of all thanks for all your efforts on the app! I was looking for a reliable cross platform keypass client alternative, and this stood out for me!

Wanted to check is the project still active, and are the devs planning on reviving the same? Not seeing many commits, respnses on github issues/even on authpass forum. 

Thanks again for all your hard work on the project! :)

**Comment by hpoul** [comment]
Yes, feel free to submit PRs. My time is currently occupied by paying projects, but I'll happily reviews PRs
