### ISSUE TITLE
修改合并数据库导致其他端的应用无法识别 比如keepass2andriod iOS的奇密

### ISSUE THREAD

**Issue by nmsglmg** [authpass/authpass#364]
从该应用打开其它端同步过来的文件，只要他修改过或者合并过就只有他自己能打开，其他开源的keepass系列的都打不开，目前原因未知，上一次体验还是在前年，现在还没修复，也是奇怪🆘🆘🆘

**Comment by hpoul** [comment]
sorry, I don't speak.. whatever language that is.
