### ISSUE TITLE
kdbx 4.x compatibility (dart misses argon2)

### ISSUE THREAD

**Issue by hpoul** [authpass/authpass#4]

**Comment by hpoul** [comment]
Awaiting full ffi support ;-) maybe investigate https://github.com/rushio-consulting/libsodium.dart

**Comment by hpoul** [comment]
I have just committed (experimental) support for kdbx 4.x - anyone willing to test it? i could create a beta build for any platform (android, ios or macos) :-)

**Comment by Cogitri** [comment]
I can test this on Android.

**Comment by BeneCollyridam** [comment]
@hpoul I can also test on android

**Comment by hpoul** [comment]
@BeneCollyridam that would be nice, it is already available in the latest google play version.. maybe you can let me know if it works for you?

**Comment by BeneCollyridam** [comment]
@hpoul I am not able to open my kdbx 4.0 database (app version 1.5.0).
When I try to load it I get a error "Unsupported operation: unsupported encrypt stuff"

**Comment by hpoul** [comment]
@BeneCollyridam ah yes, kdbx 4 right now only supports argon2 .. i thought everyone using kdbx 4.0 uses argon2 .. okay.. so support for AES-KDF is still missing.. thanks for testing.. i'll look into it.. it shouldn't be too hard to add support

**Comment by hpoul** [comment]
@BeneCollyridam AES-KDF is now supported in the latest 1.5.2 version. it is already available on play store. maybe you can give it a try and let me know if it works for you.

**Comment by BeneCollyridam** [comment]
It works now!

**Comment by hpoul** [comment]
🎉️thanks for testing :-D if you've got other problems/incompatibilities let me know.. or any pressing missing features.. helps me prioritise ;)

**Comment by ucodelukas** [comment]
Works

**Comment by Sherlock-Holo** [comment]
@hpoul could you update the readme, if authpass has supported kdbx 4.x :)
