### ISSUE TITLE
Allow changing master password

### ISSUE THREAD

**Issue by hpoul** [authpass/authpass#46]
When using 'save as' for example, create a way to set a new master password, and also optionally create/reencrypt using keyfile. (decrypt with keyfile see #3)

**Comment by hpoul** [comment]
Changing the master password is now implemented in 1.9.2 (1831) - If anyone wants to test it, it would be nice if you could let me know if it works 😅️ It's in the 'manage file' screen. It [should be available on play store dev/beta and ios testflight](https://authpass.app/docs/help-us-beta-testing/).

<img width="551" alt="Screen Shot 2021-08-16 at 16 13 24" src="https://user-images.githubusercontent.com/313066/129577593-185c0e9b-98c8-4a5b-a3d6-f344f20c2836.png">

Otherwise i'll probably release it soon'ish.

Generating master passwords is still open, I've created #256 for that.

**Comment by Turux** [comment]
Just tested it, it works perfectly!

That's such a great addition to the app! Thanks!

**Comment by hpoul** [comment]
@Turux thanks for testing! I've now gone ahead and released 1.9.2 🥳
