### ISSUE TITLE
Can't use a database in Nextcloud

### ISSUE THREAD

**Issue by northorsouth** [authpass/authpass#48]
Hi guys,

I have a keepass database stored on my nextcloud server. I'm trying to use an f-droid app to access it. Authpass seems to be the only keepass app that works with Webdav but I'm getting some strange errors. 

When I first open the app, I get a window that says: "Error while Quick unlocking files. MissingPluginException(No implementation found for method canAuthenticate on channel biometric_storage)"

I can "ok" past that but I get another error after I enter my nextcloud credentials and try to connect:
"Error while authenticating. Error while trying to authenticate fo google drive. Storage Exception{type: StorageExceptionType.unknown, details: Error during request. (405 Method Not Allowed, errorBody: }"

Anyone know what's going on?

I'm using a Moto G7 Power.

**Comment by northorsouth** [comment]
Apologies actually, I wasn't using nextcloud's webdav url. I still get an error when I try and log in, but it's not the "StorageExceptionType" error mentioned above. This is what I get:

"Error while authenticating. Error while trying to authenticating fo google drive. MissingPluginException(No Implementation found for method init on channel biometric_storage)"

Which seems like the same error I get on startup. No idea what it's talking about.

**Comment by northorsouth** [comment]
Thanks for the quick response. Android 9. It has a fingerprint sensor, if that's relevant information.

-------- Original Message --------

**Comment by hpoul** [comment]
@northorsouth the problem is that the f-droid version is built using flutter stable channel, while that plugin is only supported in newer flutter versions - because it also supports mac OS which required changes to the plugin architecture :-/ thanks for bringing this to my attention .. i'll have to figure out how to fix that.. probably just create a branch for supporting flutter stable..
in the meantime, do you think you could try out the [play store version](https://play.google.com/store/apps/details?id=design.codeux.authpass)?

**Comment by northorsouth** [comment]
Not sure if you have any control over this, but the Google play version just hangs on "waiting for download"

-------- Original Message --------

**Comment by northorsouth** [comment]
Ignore above comment, that was my issue.

I downloaded the Google play version and I can log in to my nextcloud instance.

However, I get this error when I try to decrypt the database:

"Unknown error while trying to open file. NoSuchMethodError: The getter 'bytes' was called on null.
Receiver: null
Tried calling: bytes"

**Comment by licaon-kter** [comment]
@hpoul and F-Droid can't build using the newer one? Which one exactly?

**Comment by hpoul** [comment]
@licaon-kter @northorsouth in the meantime the latest fdroid build should work.. as for the `The getter 'bytes' was called on null` - this is probably when loading a kdbx 3.x file.. make sure to use kdbx 2.x - the latest AuthPass version should give you an appropriate error message when an unsupported file format is opened. (see also #52)
