### ISSUE TITLE
Keypass and sync

### ISSUE THREAD

**Issue by gedw99** [authpass/authpass#49]
I saw a few issues regarding keypass support.

A quick check and found a good keypass lib for golang and so easy to make a golang server with pub sub integrated.

https://github.com/tobischo/gokeepasslib

I can help integrate the golang and flutter is you up for it.

A user will need to use another form of suthication to access the keypass server ironically. If you have any preferences I can implement it. Maybe just a long passord. ?

**Comment by hpoul** [comment]
@gedw99 sorry for the late reply, somehow missed the notification. I am not sure what exactly you are proposing. the keepass support is all on the client side. there is no easy way to have a native interface between go and flutter. But there would be a (experimental) dart ffi support which can interface with C code. The biggest hurdle for keepass 4 (kdbx 3.x) support is missing argon2 support in dart. So the way to go would be to make argon2 available through dart ffi i guess..

**Comment by hpoul** [comment]
fyi, if you mean in reference to #20 - this was meant as a transparent sync service, the server wouldn't need to know anything about keepass/kdbx file format. As it should never be able to read the passwords anyway..
