### ISSUE TITLE
AuthException when trying to save password with biometric

### ISSUE THREAD

**Issue by krodelabestiole** [authpass/authpass#50]
AuthPass 1.2.1+115 (play store build)
on lineageos 15.1 + microG

I can't save password with biometric key store. And file opening fails (both local or webdav).
Biometric works fine with other apps and I can open kdbx files without selecting the biometric save option.

Here is the complete error message I have as soon as I touch the fingerprint sensor :

```
Unable to open File
Unknown error while trying to open file. Instance of 'AuthException'
```

**Comment by hpoul** [comment]
@krodelabestiole sorry for the late response. Could you please verify if this problem still occurs on the latest version (1.2.8)? thanks

**Comment by krodelabestiole** [comment]
Do you mean 1.5.8 ?

Yes same problem, same error message.

**Comment by hpoul** [comment]
@krodelabestiole can you please send me the log file via the app bar menu > email support? Thanks

**Comment by krodelabestiole** [comment]
done.

**Comment by hpoul** [comment]
thanks, unfortunately the log file does not help too much in this case it seems.. "User not authenticated"
imo this must be something lineageos specific, although there are quite a few inconsistencies in the security APIs.. i have updated the androidx compatibility libraries to their latest versions, you could try if that changed something: https://github.com/authpass/authpass/actions/runs/101472162 ("app-sideload-release-1117.apk"). This build also adds a few more details to the log file.. so you could send it to me again if it doesn't work, maybe we're lucky..

other than that, if you do have the adb tools installed, you could try to get a logcat of the app.. maybe there are some more clues in the native logs.. (the log files for "Email Support" only contain logs produced by the app itself, not potential error messages by the android system).

thanks

**Comment by kapcom01** [comment]
Hello, I have the same problem on Lineage 16.0 with AuthPass 1.6.1 from F-droid.
Should I post the app.log.txt here?
Also I have adb tools and Android Studio installed if you want me to test anything.

Thanks

**Comment by hpoul** [comment]
@kapcom01 yes, log file would be helpful.. you can simply use the inapp email function to support@authpass.app .. (the log should not contain anything sensitive, but it's still safer not to post it publicly) -- if the log file won't help, i might come back to you regarding adb logcat :-) thanks

**Comment by hpoul** [comment]
thanks for the log.. although it does not really help much :-( to be honest i kind of suspect a bug in lineageOS.. (maybe in combination with the androidx.biometric library). e.g. https://review.lineageos.org/c/LineageOS/android_system_keymaster/+/265310 sounds a bit like it.. unfortunately hard to know.. the only other clues of that error message were at https://github.com/Kunzisoft/KeePassDX/issues/114 .. maybe you can give that a try? https://github.com/Kunzisoft/KeePassDX/issues/114#issuecomment-531467569

> The solution I found is to delete fingerprints from the device and save them again. 

you could try looking into logcat if there are any more clues what could cause that error.. but i kind of doubt it :-(

fwiw. the error message is (maybe there is something coming before that only visible in logcat..):
```
PlatformException(AuthError:Unknown, Unexpected authentication error. User not authenticated, android.security.keystore.UserNotAuthenticatedException: User not authenticated
android.security.keystore.UserNotAuthenticatedException: User not authenticated
        at android.security.KeyStore.getInvalidKeyException(KeyStore.java:884)
        at android.security.KeyStore.getInvalidKeyException(KeyStore.java:926)
        at android.security.keystore.KeyStoreCryptoOperationUtils.getInvalidKeyExceptionForInit(KeyStoreCryptoOperationUtils.java:54)
        at android.security.keystore.KeyStoreCryptoOperationUtils.getExceptionForCipherInit(KeyStoreCryptoOperationUtils.java:89)
        at android.security.keystore.AndroidKeyStoreCipherSpiBase.ensureKeystoreOperationInitialized(AndroidKeyStoreCipherSpiBase.java:265)
        at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineInit(AndroidKeyStoreCipherSpiBase.java:109)
        at javax.crypto.Cipher.tryTransformWithProvider(Cipher.java:2984)
        at javax.crypto.Cipher.tryCombinations(Cipher.java:2891)
        at javax.crypto.Cipher$SpiAndProviderUpdater.updateAndGetSpiAndProvider(Cipher.java:2796)
        at javax.crypto.Cipher.chooseProvider(Cipher.java:773)
        at javax.crypto.Cipher.init(Cipher.java:1143)
        at javax.crypto.Cipher.init(Cipher.java:1084)

```

**Comment by hpoul** [comment]
If anyone is still experiencing this problem, please try to delete fingerprints and readd them, if this fixes the problem, otherwise please comment again.
In the meantime i'll close this issue. If you still have those problems, don't hesitate to reopen.
