### ISSUE TITLE
WebDav: "propfind requests with a depth of infinity are not allowed for"

### ISSUE THREAD

**Issue by frankhommers** [authpass/authpass#53]
My WebDAV server (Synology) denies the request directly after clicking OK on the WebDav settings screen.

The server says: "propfind requests with a depth of infinity are not allowed for".

I would like the ability to enter a full URL directly to the webdav file. That way it should work..?

**Comment by frankhommers** [comment]
Ah, I saw you hadn't implemented keyfiles yet. So that makes it not usable for me even if this would get implemented. So this is definately lower priority ;-)

**Comment by hpoul** [comment]
@frankhommers well, the kdbx library already supports it.. so wouldn't be much work to add keyfile support.. how do you get to your keyfile? Also webdav, or locally? Btw which platform are you using?


Re webdav - I'll take have to take a look.. i actually also implemented a browser, not just abrecursive search.. which would work i guess?

**Comment by hpoul** [comment]
@frankhommers that's funny.. it looks like nextcloud defaults "Depth" to 1, not infinity 🤔️but the good news is, that it's easy to fix.. I've just added the Depth header. What platform are you using? maybe I can give you a beta version to try it out..
also, key file *reading* is already supported.. i've just forgot to close the Issue. The only remaining is creating a new password database with a key file.. but reading should work, as long as you have the key file locally on your device.

**Comment by frankhommers** [comment]
I run my WebDav on Synology. Depth 1 would work.
I run the app on iPadOS.
I have my keyfiles locally.
I know the direct full webdav url to the kdbx file. So entering the full url would work also. But depth 1 probably too ;-)

**Comment by frankhommers** [comment]
I have checked out the newest release. The browsing for the keyfile (locally on iPad) and then browsing for the WebDav now just works fine! Great.

Unfortenately my kdbx is huge, and it crashes when the loading spinner is animating...

**Comment by hpoul** [comment]
Sorry to hear that.. do you see any error messages? Otherwise in the menu top right should be an option to send email to support which includes the log file, can you try this maybe? Thanks

**Comment by frankhommers** [comment]
I've sent you an email. But I don't think there is enough info to fix it ;-)

**Comment by frankhommers** [comment]
FYI. It started to work after I rebooted my iPad.

I would really love folders in the app so that AuthPass doesn't need to load and show everything, because it's a lot and it really slows down the app.

**Comment by hpoul** [comment]
@frankhommers that is weird, reboot should but change anything.. but anyway :)
The latest version actually has very basic support for groups. When you press the"sitemap" icon in the app bar your get a list of the open files, web you tap the arrow you will see your groups. An tapping on a group it will show you only the password entries of that group.. 
If you have any suggestions how to improve that flow, let me know.. I'm not really a heavy user of groups, i typically just dump everything into the root group 🤷‍♂️

**Comment by hpoul** [comment]
i close this issue, since webdav support should work already. if you have any further problems/suggestions regarding groups maybe open a new issue. thanks
