### ISSUE TITLE
[android] Integrate crash reporting (e.g. acra)

### ISSUE THREAD

**Issue by hpoul** [authpass/authpass#63]
Integrate some form for crash reporting. Especially useful for distribution outside play store.

See  https://github.com/ACRA/acra

**Comment by SAGARSURI** [comment]
Hey @hpoul 
Curious to know why only specific to android? Why not use Crashlytics for flutter which will take care of all types of crashes.

**Comment by hpoul** [comment]
@SAGARSURI I'm using crashlytics for other projects, and i seriously hate all of firebase. It has way too many dependencies, and crashlytics also does not support desktop or web anyway.. 
And i would also like something which can be used in fdroid builds..

**Comment by SAGARSURI** [comment]
So you want to monitor only the android specific crashes if we go ahead with ACRA.

**Comment by hpoul** [comment]
@SAGARSURI since there is no single solution for android,ios,macos,desktop,windows .. specific solutions which are as small as possible are preferable.. i think acra also does not need a server component and can simply send emails? I think that would be a great solution for now.

**Comment by SAGARSURI** [comment]
Did you check Sentry.io ?? It's supported for android, iOS, web. If that doesn't meet your needs than we can pick platform specific solutions. But maintaining all those dashboards can be a bit messy in long terms. If we have a centralised board than it would be really great.

**Comment by hpoul** [comment]
I don't think sentry.io would work out for fdroid.. and.. i guess either one solution which supports *all* platforms (2/5 or 3/6 is not really worth the effort). and I seriously hope there aren't a million crashes :-) this is *only* the native part, which is very minimal anyway. Of all play store installations, there was a single crash within the last month. :-)

this issue is basically about knowing when fdroid users experience crashes.. play store and app store crashes are already registered in the respective stores. - Also, getting crashes by email to support@authpass.app is already kind of "centralised board" because when users send error log files within the app, it also lands in that email box ;-)

**Comment by SAGARSURI** [comment]
I guess you already have a solid solution for monitor crash reports. Adding ACRA won't be needed I believe. But if you insist then I can take it up 😄
