### ISSUE TITLE
Request to allow adjustment of fontsize in OSX application

### ISSUE THREAD

**Issue by abawany** [authpass/authpass#69]
I am now using the application on OSX in addition to iOS. I was wondering if there was a way to adjust the font size of the various elements.

**Comment by hpoul** [comment]
Not right now, what exactly are you looking to customize? Ie. Which text elements, and larger or smaller? :)

Btw thanks for the donation 🙏 should probably start a sponsors list :-)

**Comment by abawany** [comment]
I was hoping the text elements could be made smaller for the groups and entries - on my display, they appear large and I would like to be able to reduce their size. Thank you again for your work on this excellent application.

**Comment by hpoul** [comment]
sure, shouldn't be too difficult.. out of curiosity, is it exorbitant larger than (other) mac apps? could you share a screenshot in comparison, for example compared to the settings screen:

<img width="211" alt="Screenshot 2020-05-14 at 08 24 00" src="https://user-images.githubusercontent.com/313066/81900149-94bc9a80-95bc-11ea-92b5-fcbdb8f097f1.png">

for me it looks like the font size in the System Preferences is approximately the size of the subtitles in the password list.. (ie. usernames). In the screen shot "General" in the System Preferences vs. "herbert" in the password list.

If it's larger for you, than I should figure out a way to correctly size the fonts.. otherwise i'll just have to provide a preference setting for the font sizes :-)

**Comment by hpoul** [comment]
i have played around a little bit.. not sure if it's a good idea to make it that configurable.. but we'll see :-) (would still be interesting how your "default" looks on your screen)

![fontscale](https://user-images.githubusercontent.com/313066/81915575-13243700-95d3-11ea-982d-86e5e8f1c8dd.gif)

**Comment by abawany** [comment]
I have attached two screenshots to show how the different in sizes in the entries - it seems that the spacing between the entries exacerbates my perception of the font size though the latter appears 50% larger to me as well. I like the visual density approach above as it will address the spacing and the font size consideration as one.

![Screen Shot 2020-05-14 at 12 38 40](https://user-images.githubusercontent.com/821103/81967006-e7f41480-95df-11ea-8f50-2cd00d5c4997.png)
![Screen Shot 2020-05-14 at 12 38 58](https://user-images.githubusercontent.com/821103/81967011-e9bdd800-95df-11ea-8d7f-3561aa9026c3.png)

**Comment by abawany** [comment]
Thank you for releasing the change in 1.6.1 to allow for adjustments to Visual Density and Text Scale - it really helps with the look-and-feel and usability of the application for me by making the font and spacing comparable to the other apps on this machine.

**Comment by hpoul** [comment]
you're welcome ;) can you provide another screenshot how you are using it now? i'm curious ;)

i wonder if i just got used to how it looks, or if I have to consider some kind of font scaling/pixel ratio from the platform.. although i have to admit, compared to e.g. the Finder it **is** bigger.. (like upper case letters in the Finder windows are about the same height as the lower case letters in AuthPass :) )

**Comment by abawany** [comment]
Sure thing. Attached are three screenshots with the first showing the current value of the new scaling settings and the resulting views. I noticed this scaling issue on osx as the font etc. looks fine on ios.

![Screen Shot 2020-05-22 at 10 39 58](https://user-images.githubusercontent.com/821103/82684822-d7afeb00-9c18-11ea-9f41-39928d38ca4d.png)
![Screen Shot 2020-05-22 at 10 40 27](https://user-images.githubusercontent.com/821103/82684853-e26a8000-9c18-11ea-9fbc-d57743fff841.png)
![Screen Shot 2020-05-22 at 10 40 35](https://user-images.githubusercontent.com/821103/82684862-e6969d80-9c18-11ea-9eec-108fbcdf608d.png)
