### ISSUE TITLE
Unreadable fonts

### ISSUE THREAD

**Issue by cravler** [authpass/authpass#74]
![Screen Shot 2020-05-21 at 14 22 58](https://user-images.githubusercontent.com/157440/82554506-c27e8200-9b6e-11ea-88a7-ff002df81a4a.png)

macOS 10.12.6

**Comment by hpoul** [comment]
😮️ this is really strange.. are you using the latest version from the app store? or did you download the zip file? (i've just tried both.. so .. am a little confused.. and I don't think it would get through app review that broken) - although i'm using 10.15.4

what is your default locale?

**Comment by cravler** [comment]
v1.6.1 from App Store

**Comment by cravler** [comment]
![Screen Shot 2020-05-21 at 15 03 46](https://user-images.githubusercontent.com/157440/82557417-5c94f900-9b74-11ea-99c1-94517a4c8554.png)

**Comment by cravler** [comment]
on another with macOS 10.15.4 all fine

**Comment by hpoul** [comment]
Ok, my guess is, that it's font-related. AuthPass uses SF UI/SF UI Display which should be the default font on macos since macOS 10.11 (imho). Not sure why MacOS 10.12 might not have it.. although maybe it's just a matter of changed font names or something.. i'll have to investigate more.. 
maybe i'll just bundle some font.. although it would have been nice to use the system default font 🤷️

**Comment by hpoul** [comment]
Can you please give this one a try:
[AuthPass.app-1-6-2-1160.zip](https://github.com/authpass/authpass/files/4667088/AuthPass.app-1-6-2-1160.zip)

(fonts are downloaded on runtime, so it might take a few seconds) .. you can also try to press the botton on the top left a few times, which cycles through 4 different fonts

<img width="184" alt="Screenshot 2020-05-22 at 11 05 53" src="https://user-images.githubusercontent.com/313066/82651269-375bc580-9c1c-11ea-9599-7195cdbfaeef.png">

please let me know if this works on macos 10.12

**Comment by cravler** [comment]
works from start and fonts change as well

**Comment by hpoul** [comment]
thanks for testing, can you please give this one a try as well:
[AuthPass.app-1-6-2-1161.zip](https://github.com/authpass/authpass/files/4671536/AuthPass.app-1-6-2-1161.zip)

It now just bundles the `Inter` font which will be used on mac os <10.15 .. >= 10.15 would keep the default font (SF UI Desktop and SF UI Text).. if this works on 10.12 for you i'll probably just release that fix.

(the previous version used google fonts and downloaded the fonts dynamically.. which seems like a useless feature :) )

**Comment by cravler** [comment]
yes, it is works

**Comment by hpoul** [comment]
1.6.2 is already released in the app store. thanks for testing :)

**Comment by hpoul** [comment]
@cravler I was wondering, if you are still using an older MacOS 10.11? I have filed a bug report with flutter and they'd like to know if this problem still exists.. would you mind if i'll send you a test application? (I don't have a 10.11 running) - thanks

**Comment by cravler** [comment]
hi, i have macOS 10.12.6, if still needed, I can test on it.

**Comment by hpoul** [comment]
@cravler it would be helpful if you could give this one a try:
[AuthPass.app-font-try.zip](https://github.com/authpass/authpass/files/5048381/AuthPass.app-font-try.zip)

thanks!

**Comment by cravler** [comment]
![Screen Shot 2020-08-13 at 21 13 57](https://user-images.githubusercontent.com/157440/90171322-fd790600-dda9-11ea-8b37-f213d9ecd316.png)
Unreadable fonts

**Comment by hpoul** [comment]
@cravler thanks

**Comment by targor** [comment]
I have a similar Problem. The font in the app seems to work well, but i am unable to open a safe, because the file open dialog shows only gibberish texts. Can someone give me a hint? I am using it on Kubuntu.

![fonterror](https://github.com/authpass/authpass/assets/7933943/81dbbc6e-c6ed-417c-86a3-f8bd3821a471)
