### ISSUE TITLE
Translate/localize AuthPass to different languages

### ISSUE THREAD

**Issue by hpoul** [authpass/authpass#78]
**Update**: Translation started with a few strings, looking for contributors at https://translate.authpass.app/authpass ;-)

Make it possible to translate&localize AuthPass to different languages. For a start

* German
* Spanish

This is issue is just to gauge interest, so add your 👍️ to the issue if you are interested. and add a comment if you're willing to do the translation :-)

https://docs.google.com/document/d/10e0saTfAv32OZLRmONy866vnaw0I2jwL8zukykpgWBc/edit#

**Comment by roket1428** [comment]
I would like to translate it to Turkish. ^.^

**Comment by ashed** [comment]
Translate it Russian. I can help to localize resources.

**Comment by Skymirrh** [comment]
Hi! Available for French translation.

No promises as I'm currently working on other projects, but if I get back to this issue before you do, I will have a look at implementing localization itself -- I have no Dart experience but I figured this could be a good thing to start with.

**Comment by hpoul** [comment]
@Skymirrh sure would be great.. although since AuthPass has no externalized strings yet, and no support for localizations yet.. it's not the most trivial task to be honest. but if you're motivated and got time let me know.. you should get familiar with flutter and dart though.. maybe take a look at a simple hello world app. I should probably write something up on how to get AuthPass development environment running.. it's actually not really difficult.. basically just checking out the code + submodules, and running with flutter.. :)

**Comment by hpoul** [comment]
I think i'll give localizations / string externalizations a try.. anyone willing to do some translation in the next few days maybe? @ashed @Skymirrh ? Not sure yet how this will be done (either editing json files or finding a tool to do this)

**Comment by Skymirrh** [comment]
For external tools, you might want to have a look at [Weblate](https://weblate.org/) or [POEditor](https://poeditor.com/), these are the two I usually see. I personally am comfortable editing resource files directly (no matter if external tools are present or not), and actually prefer doing so in order to build and test right away, but external tools are sometimes useful for non-tech translators to get involved.

Available for translating to French, whatever you choose.

**Comment by hpoul** [comment]
To be honest those `.arb` files which are used by the flutter workflow are a pretty annoying thing to work with :-) I try to adhere to the https://flutter.dev/go/i18n-user-guide guide.. 

I've looked at a couple of tools now, right now i tend to lean towards [crowdin](https://crowdin.com/) because they seem to handle plurals at least a little bit, which i liked:

<img width="712" alt="Screenshot 2020-08-07 at 15 01 35" src="https://user-images.githubusercontent.com/313066/89648045-e5dbe200-d8be-11ea-937c-948f1047146e.png">

The hosted version of Weblate did not accept `.arb` files, I've also tried the self hosted version, but that was also a bit annoying.. Yeah, maybe doing it manually is the way to go.. although it's nice to have a UI to check for completeness, etc. :-)

**Comment by Skymirrh** [comment]
Strange, Weblate's documentation seemed to mention ARB support: https://docs.weblate.org/en/latest/formats.html#arb-file
And POEditor: https://poeditor.com/localization/files/arb & https://poeditor.com/kb/how-to-translate-flutter-apps-using-arb-files

For reference, POEditor seems to support plurals as well: https://poeditor.com/kb/plural-forms

**Comment by hpoul** [comment]
Weird.. at least after importing the arb file into POEditor the plural did not work.. but maybe I did something wrong.. it just showed a plain text box.. it did not seem to recognize that this was supposed to be plural field.. 

<img width="1203" alt="Screenshot 2020-08-07 at 15 53 44" src="https://user-images.githubusercontent.com/313066/89652788-4cb0c980-d8c6-11ea-9607-c11448738495.png">

**Comment by hpoul** [comment]
I have now started externalizing a few strings. (I've basically done Launch screen, preferences, menu items and about dialog).
The base strings are all in https://github.com/authpass/authpass/blob/master/authpass/lib/l10n/app_en.arb .. 
@Skymirrh do you think you could also help with externalizing the strings? It's basically going through the files, copying the strings to app_en.arb - this will autogenerate the related properties in `AppLocalizations` and then using those properties in the code:

https://github.com/authpass/authpass/commit/da328bb2f50e209cd10b6ce8a7a9a0a19f41ba00#diff-2093d39b91124066d2d0ace185c6e9dcL52-L71

**Comment by Skymirrh** [comment]
Sure, I could do that, though I'm not sure if I'll have free time in the next few days. So it depends on how quick you'd like this to be done :D

**Comment by hpoul** [comment]
@Skymirrh I don't have deadlines 😅️ Would be greatly appreciated, then I would focus on other issues :) there is no hurry I guess.. Do you have experience with flutter? There's a short intro how to get AuthPass to compile/run in the [CONTRIBUTING.md](https://github.com/authpass/authpass/blob/master/CONTRIBUTING.md), i'm also on the [discord channel](https://discord.gg/Nuraxmc)

**Comment by hpoul** [comment]
@Skymirrh no pressure, just wanted to check in to make sure it's not forgotten :-) still interested in getting into this in the next few weeks?

**Comment by Skymirrh** [comment]
Not forgotten, it's in my backlog of things to do :) Not sure when I'll get around to it, I got some other contributions I'd like to finish first (notably Grav-related stuff).

**Comment by hpoul** [comment]
I have now started with a couple of strings.. and also created a project on crowdin. So if anyone want to already start translating (@ashed ? ;) ) it's now possible at: https://authpass.crowdin.com/authpass :-) I've started to do a few german translations.. 

(there are still 90% of strings hardcoded.. so it will take a while before everything can be translated there.. but it's a start :))

**Comment by hpoul** [comment]
Small status update, since AuthPass is now already shipping with multiple languages :-)
Im basically slowly starting to externalize strings, while adding features or cleaning up - I brought it down to ~590 string literals in the code. So there is still plenty left to do if anyone has some time on their hands 😅️ otherwise i'll just externalize every now and then..

<img width="642" alt="Screen Shot 2020-09-19 at 13 11 07" src="https://user-images.githubusercontent.com/313066/93665805-c0272880-fa79-11ea-811d-e76fd125587c.png">

(many of those string literals are probably valid non translatable strings, but my goal is to mark all NON-NLS strings as such, or make them translatable).

**Comment by hpoul** [comment]
Finally externalized **all remaining strings** 🥳  No more (non-ignored) string literals anywhere in the (dart) code ;-)

<img width="647" alt="Screen Shot 2021-08-06 at 14 02 27" src="https://user-images.githubusercontent.com/313066/128507576-352b1929-00e3-4ead-afe2-b9dcb3315ed8.png">

And there's a github action which checks for new string literals, so we should stay this way.

The only thing missing are the translations https://translate.authpass.app/
