### ISSUE TITLE
F-Droid: Seems I can't save any new or updated entries

### ISSUE THREAD

**Issue by TobiasDev** [authpass/authpass#79]
I have a file locally synced to my phone through the NextCloud android client (since the WebDAV sync  doesn't allow me to see my passwords when I'm offline). However, whenever I try to add a new entry or update an old entry and press save it seems to not have been saved.

1. The app tells me to save before I exit, I press save and it still says the same over and over again whenever I try to exit the new or updated entry. 
2. My Nextcloud file never shows that it has been updated.

Do you happen to know if this is an issue or if I need to do something special to be able to save my entries? 

Thanks, 
Tobias

**Comment by hpoul** [comment]
Sounds like a problem while saving the file.. did you select the file through the document picker dierctly from nextcloud client, or is the nextcloud client syncing into the file system and you select it from there?
maybe take a look at the log, or send it, thanks

**Comment by TobiasDev** [comment]
> Sounds like a problem while saving the file.. did you select the file through the document picker dierctly from nextcloud client, or is the nextcloud client syncing into the file system and you select it from there?
> maybe take a look at the log, or send it, thanks

I pick from the authpass file-picker and choose the file synced through NextCloud. It syncs to its own folder and should upload / download when it sees changes.

Is there any sensitive data I need to hide in the log? Or something I can look for to see the problem and narrow it down to send?

**Comment by hpoul** [comment]
Re logs: i typically try to keep sensitive data out of the log, but until you double check i wouldn't post it publicly.. 
I would hope that it contains some exception or error message.. you can check if there are any WARNING or SEVERE messages

**Comment by TobiasDev** [comment]
I have removed all data I believe could be sensitive (it wasn't really, but it just feels better not sharing where it is stored and such since that included my NextCloud address. :)). Do you want me to post the log here or send it in an email? 

I didn't really find any SEVERE or WARNINGs in it though. However, I could have missed it.

**Comment by hpoul** [comment]
feel free to send it to herbert@authpass.app or support@ doesn't really matter :-)

**Comment by hpoul** [comment]
thanks for the log.. it's a bit strange though.. have you tried selecting the file through the file picker in the latest version if that changes anything? (the previous versions used a different file picker and tried to directly write to the file, while the new version should  keep a security scoped  uri)

**Comment by TobiasDev** [comment]
Hmm. I tried opening the file with the new file picker but still have the same issue.

**Comment by hpoul** [comment]
have you checked the log whether is exactly the same error?
```
(OS Error: Permission denied, errno = 13)
#0      _File.open.<anonymous closure> (dart:io/file_impl.dart:366)
```
?

**Comment by TobiasDev** [comment]
Yep. Has the same line in it.

**Comment by hpoul** [comment]
this is honestly a bit weird.. anyway i'll have to somehow reproduce this.. which android version are you using, and is this happening with all files or only files you are syncing to nextcloud?

(fwiw, offline support for webdav/dropbox/google drive would definitely a useful feature as well..  I've created #80 for this.. this has been bugging me personally as well..)

**Comment by TobiasDev** [comment]
I haven't tried another file yet. I want to try something as well. I want to create a new file in Authpass, upload it too my NC instance, download it and see if the same thing happens.

I'm on LineageOS 16.0 with MicroG and use a OnePlus 3.

**Comment by TobiasDev** [comment]
I have just discovered something that is weird but a solution.

When I add something new or update something, I add it, press save and then want to leave the entry. This is all pretty fast. 

When I then try to leave the entry it says it still haven't saved my entry. Then I save again, and get the same message. However, this morning I saved and someone asked me something (which means I waited something like 30 seconds or such before trying to leave). This time the app didn't say anything, but had actually saved the entry. I saw the Floppy Disk in the top right corner disappear. 

Because of this I tried doing this: 
1. Create a new entry
2. Add dummy info to all fields (since this was just a test)
3. Press Save
4. Wait a bit
5. The Floppy Disk in the top right corner went away after something like 10-15 seconds. 
6. I went out of the entry and it didn't complain about not being saved
7. I double checked on NextCloud and yes the entry had been changed

It seems like if I wait a little bit it does actually save my entry and update my file.

I also tried to update an entry following the same process and also then I didn't have any problems anymore. 

I would say we can probably close this issue since it looks like Android needs a bit of time to update the file before leaving and therefore the app complains. Maybe it is something NextCloud file sync specific? 

However, I would still love to see WebDav offline support since that means I don't have to have the file synced through the NextCloud client. But just only have it synced through AuthPass which I would prefer. :)

**Comment by hpoul** [comment]
this sounds pretty weird.. especially with that error message.. are you certain that on your last try you saw the error message appear again in the logs (ie. with a new time stamp)?
I guess it *could* take some time to save.. but then there should be no error message.. and in that time the floppy disk icon in the top right corner (and the save button) should be disabled for the time it is saving..

**Comment by TobiasDev** [comment]
Yeah, I'm 100% sure I saw the error message, but I'm also confused as to why it works. I will try checking a new log and see if I still see the error.

**Comment by TobiasDev** [comment]
Yep, I even now have it in a new log I created (and in this one I never got the error message at all since I did the waiting)

`FileSystemException: Cannot open file, path = '/storage/emulated/0/Android/path/to/file.kdbx' (OS Error: Permission denied, errno = 13)
#0      _File.open.<anonymous closure> (dart:io/file_impl.dart:366)
#1      _rootRunUnary (dart:async/zone.dart:1192)
`

**Comment by hpoul** [comment]
i'm still a bit confused.. a few questions, hope you don't mind :)

1. So you don't have an error message when you wait?
2. when exactly is the error log appearing? When you click "back" and "Discard"?
3. do you see the save button being disabled for some time after you tap it?
4. you only have that one file open?

**Comment by TobiasDev** [comment]
1. Nopp, then I don't get the error message (maybe I shouldn't say error message since it is more a warning that my file has been changed, but not saved). But, yes, when I wait, I do not get the message. 
2. When I click back after modifying my entry
3. Yep, I do, it looks disabled for some time before disappearing. 
4. Yeah, I only have one file open. 

And I don't mind answering it all! Anything that helps you out. :D

**Comment by hpoul** [comment]
with error message i actually meant the error in the log file, not the warning in the UI :-)

I still can't quite figure out what action triggers the exception in the log file, as far as I understand it, you click the 'save' button and immediately click on 'back' without waiting.. this is when changes are not persisted. but when you click 'save' and wait until it disappears everything works?

**Comment by TobiasDev** [comment]
Yep, exactly like you wrote. :)

**Comment by hpoul** [comment]
maybe you can give this build a try when you've got time: https://send.firefox.com/download/678bddede88fab69/#6aVLgYA86tsSCufrv1rR1w
i have just added some more logging to see how it is saving the file.. maybe that can give some idea what's going wrong

**Comment by TobiasDev** [comment]
Sorry for taking so long! Been a pretty hectic few days, but I have just sent the new log file to you. :)

**Comment by hpoul** [comment]
@TobiasDev sorry I somehow missed this one.. do you still experience this problem?

**Comment by TobiasDev** [comment]
Nopp, it is all gone! I can close the issue. :)
