### ISSUE TITLE
Offline support when using online storage endpoints, conflict detection and merging

### ISSUE THREAD

**Issue by hpoul** [authpass/authpass#80]
We should keep a cached version of the file in case the user wants to access/save the file while offline, and then sync it once we are back online.

I assume it could be a bit of a problem with overwriting changes.. but most of the time we should be able to deal with it..

**Comment by TobiasDev** [comment]
> I assume it could be a bit of a problem with overwriting changes.. but most of the time we should be able to deal with it..

I don't know how difficult this would be to add, but maybe giving the user a pop-up saying that the file has been changed (checking the last update timestamp if possible) and then giving the user an option to overwrite or keep the file on the synced storage.

**Comment by hpoul** [comment]
well.. right now all external storages (except google drive) send the original etag while uploading, and it will just fail when the file was changed remotely since the last download. so we would have to catch that error and deal with it.. either ask the user, or try to merge the change.. in most cases it would be quite trivial to merge changes, as long as different entries where modified.. in a perfect world we would fetch the new version, merge local and remote.. and save :-)  but I think this is a long-term goal :)

i think in the near term it would be sufficient to try to periodically check for updates and make sure the user always only edits the most current version :) and show an error on conflicts.. (right now the only way out of a conflict would be for the user to manually select 'save as' from the options menu to not lose the changes)

**Comment by Skymirrh** [comment]
If we want to avoid conflicts, we should probably rely on [database-level synchronization](https://keepass.info/help/v2/sync.html) rather than file-level synchronization :)

**Comment by hpoul** [comment]
@Skymirrh I definitively agree.. but a first step is to recognise conflicts (ie. not override changes) :-) synchronization is a much larger project.. from the page you've linked:

> The synchronization algorithm is rather complex and it would take many pages to describe in detail how it's working

😅️

**Comment by hpoul** [comment]
I've now started implementing "synchronizing" of files (ie. merging in files where both contain *some* changes, not two completely different files).. anyone willing to test it, once it's ready? :-)
or even better.. anyone can create a test case (or two) like two kdbx files (preferable by a third party app) where items are created, moved, deleted, changed, binaries added, removed.. and for 3rd party apps maybe also "weird" properties like autotype config, foreground/background color (?), tags, "OverrideUrl" (whatever that is)

@TobiasDev @Skymirrh @christianfl ? (\*spamming all reactions* 😛️)

Just in case I miss testing some weird edge cases :-)

**Comment by TobiasDev** [comment]
I might be able to test this, however, sadly not for another two weeks. I'm currently on vacation and I'm not really on my phone or PC a lot then. :D

**Comment by christianfl** [comment]
> [...] anyone willing to test it, once it's ready? :-)
> 
> @TobiasDev @Skymirrh @christianfl ? (*spamming all reactions* 😛️)
> 
> Just in case I miss testing some weird edge cases :-)

Yes, I am! Would backup my keepass file which contains about 150 entries and use it in connection with KeepassXC and ownCloud on Fedora.

**Comment by hpoul** [comment]
@christianfl that would be great.. although in the beginning you might want to be a more gentle :-) anyway, very trivial cases at least seem to work https://github.com/authpass/kdbx.dart/blob/master/test/merge/kdbx_merge_test.dart .. I hope i can also start testing a bit more sophisticated changes and actually build it into AuthPass so it can be tested with a UI.. probably in a day’s  or two it should be ready for testing...

I guess I'll already wire it up into the save process, when a change is detected during saving, it merges bevor saving.. is probably the easiest for blackbox testing :-)

**Comment by hpoul** [comment]
@christianfl I've now implemented a very rudimentary UI to manually trigger a merge - in the file management is now a **reload**. Which platforms are best for you to test? except iOS and android can be downloaded from https://data.authpass.app/data/artifacts/ (builds >= 1460)

![merge-screencast](https://user-images.githubusercontent.com/313066/91991643-6e6d6700-ed33-11ea-9749-78945341eef4.gif)

not very user friendly.. but anyway :-) the important thing in the header is `merged` instead of `error` 😅️ and you can look at the log file to see what it has done, especially this message:

<img width="339" alt="Screenshot 2020-09-02 at 15 47 16" src="https://user-images.githubusercontent.com/313066/91991754-952b9d80-ed33-11ea-8de4-cc1f0f67abf8.png">

this should give a broad overview of the changes.

(after the merge the file is dirty, and not saved.. yet)

**Comment by christianfl** [comment]
I would like to test Android, will start this weekend!

**Comment by hpoul** [comment]
@christianfl 👍️ thanks, you can either join the beta app via google play: https://play.google.com/apps/testing/design.codeux.authpass.dev or sideload the apk.

fwiw, i have fixed a ton of kdbx file related bugs, i should probably release that sooner than later, maybe i'll try to rollout those fixes before the whole merging opens new possibilities for bugs 🤔️

**Comment by christianfl** [comment]
Yeah, I would second that!

**Comment by hpoul** [comment]
@christianfl fyi, I have now jumped the gun and released the version `1.7.6` merging is still just hidden inside the file management ("Reload"). So if you've got time it would still be great if you could test it as well. In future releases I hope to use this feature automatically when a conflict is detected.

@TobiasDev 1.7.6 now also includes the local cache for online storage. So opening a password file while offline should work, but *will* display a subsequent error message.. So it's not completely solved, as I still have to figure out how to alert the user of being offline.. but it should still work.

**Comment by christianfl** [comment]
Hey! Tested it a bit so far. Seems that deleted entries on remote server don't get deleted within authpass. Am I right?

Merging new entries with custom fields, notes, etc. seem to work fine!

**Comment by hpoul** [comment]
> Seems that deleted entries on remote server don't get deleted within authpass. Am I right?

@christianfl big thanks for testing! actually deleted entries should get deleted.. I'll have a look.. do you mean with "deleted" moved into recycle bin, or physically deleted from the file?

(i guess better to delete too little than too much 😅️)

**Comment by christianfl** [comment]
I moved them into recycle bin in KeepassXC, cleared the bin and within authpass after reloading it showed a "merge" but the entries were still there 🤔

**Comment by hpoul** [comment]
@christianfl sorry for the delay 😅️ . I finally reproduced that problem and fixed it :-) It's in the latest beta builds for android/ios .. I think I will now start to wire it up to be automatically used when a conflict is detected when saving.

**Comment by christianfl** [comment]
No problem! Know the struggle with developing and maintaining an app by myself (I do that on Codeberg). Currently using keepass2android but I readily test your app from time to time again!

**Comment by hpoul** [comment]
I've now wired up conflict detection with merging. When a conflict is detected upon save, a merge is triggered automatically before saving. If this happens a small alert dialog will show it, just to inform the user. I guess this can be removed once it has been used often enough :)
<img width="912" alt="Screen Shot 2021-08-01 at 10 32 50" src="https://user-images.githubusercontent.com/313066/127764740-e4137a1f-e5eb-4fcb-86c6-ede5cd63e298.png">

I might change the wording in this release 'Conflict' sounds a bit too much like an error message 🤔️

conflict detection should now work in all cloud storage backends (WebDAV, Dropbox, Google Drive (pretty workaroundish #34), One Drive). But not when using the local file system.

So as long as there are no bugs discovered i'm going to close this issue for now :-) 🤞
