### ISSUE TITLE
Mac OSX Catalina 10.5.5 - can not add attachment

### ISSUE THREAD

**Issue by r3code** [authpass/authpass#93]
When I press the Add Attachment button nothing happens (
Drag-Drop not working too.

**Comment by hpoul** [comment]
Thanks for reporting the problem. I somehow missed that one. I've now fixed it, if you like you can give the attached file a try: 
[AuthPass.app-1-6-4-b1221.zip](https://github.com/authpass/authpass/files/4792517/AuthPass.app-1-6-4-b1221.zip)

**Comment by hpoul** [comment]
will be included in the next release, if you still experience problems with 1.6.4 let me know (either wait for the release or try the above build)

**Comment by r3code** [comment]
> Thanks for reporting the problem. I somehow missed that one. I've now fixed it, if you like you can give the attached file a try:
> [AuthPass.app-1-6-4-b1221.zip](https://github.com/authpass/authpass/files/4792517/AuthPass.app-1-6-4-b1221.zip)

I've checked it. Success! I can attach files now (via pressing Attach button)
