### ISSUE TITLE
Can't connect to ownCloud's webdav

### ISSUE THREAD

**Issue by nesimtunc** [authpass/authpass#96]
URL: https://owncloud.mydomain.com/remote.php/webdav/

Different errors on MacOS and Ubuntu. 

And why don't you let us paste the URL in the box?

Here's error messages screen capture for each Operating System:

**Mac OS**
![Mac OS Capture](https://user-images.githubusercontent.com/680806/85935414-8091ea00-b92b-11ea-8a27-6670ebbc60d4.png)

**Ubuntu**

![Ubuntu Capture](https://user-images.githubusercontent.com/680806/85935459-fd24c880-b92b-11ea-9dd5-316f8fc87fea.png)

**Comment by hpoul** [comment]
Linux: Good point, right now credentials for cloud storage are saved in the keychain.. unfortunately this is not yet supported on Linux.. maybe you can use something like davfs to locally mount your webdav?

I've got to look into it if there is a common keychain like API for Linux.. i guess the closest would be gnome keyring


MacOS: this is weird.. sounds like it can't access the url you entered.. are you using a proxy or something? You could try on the command line to use curl https://.. whether it is working..
Also, do you have a valid, trusted ssl certificate for your webdav server?

**Comment by nesimtunc** [comment]
No proxy, I have _Let's Encrypt_ installed which is a valid SSL Provider. I already use the same webdav for my calendars and contact. 

I couldn't curl with basic auth due to password characters :)

I don't know maybe it's related to ownCloud version. Is there a version requirement? Mine is 10.x.x

**Comment by hpoul** [comment]
what do you mean you couldn't curl due to passwords? It's enough if you get a "access denied" response.. it looks like AuthPass can't even connect.. something like:

```
➜  ~ curl https://nextcloud03.webo.hosting/remote.php/dav/files/herbert.webo.hosting@m.poul.at/
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\NotAuthenticated</s:exception>
  <s:message>No public access to this resource., No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured, No 'Authorization: Bearer' header found. Either the client didn't send one, or the server is mis-configured, No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured</s:message>
</d:error>
```

Maybe you could take a look at the log files (or send it to me). MacOS does not yet have built in support for sending the log file, but you should be able to find it in your users directory at: `~/Library/Containers/design.codeux.authpass/Data/Library/Caches/logs/` .. there should be a file called `app.log`

Either send it to me herbert@authpass.app or just search for the error message to see if there is more information (like a stack trace or similar).

thanks

**Comment by hpoul** [comment]
Please read my last comment. If you provide more details i can take a look, otherwise I close this issue, since there is nothing I can follow up on.

**Comment by nesimtunc** [comment]
Hi @hpoul 

The issue has been solved, now I can connect on my Mac but in iOS it's like this: 
![IMG_1437](https://user-images.githubusercontent.com/680806/125287820-5c4b5480-e358-11eb-9802-9b9d9234737f.PNG)

To reproduce: Click the button to Open the WebDAV screen. The Load from WebDAV button from Home Screen (2nd screen actually).

Device: iPhone 12 Mini, iOS 14.6 
AuthPass 1.8.0

**Comment by nesimtunc** [comment]
And just now on MacBook Air M1, when I tried to open another WebDAV password file, I get this error. 

<img width="912" alt="Screen Shot 2021-07-12 at 21 35 10" src="https://user-images.githubusercontent.com/680806/125288546-3bcfca00-e359-11eb-8fe8-795c908832d8.png">

**Comment by hpoul** [comment]
@nesimtunc can you please send me the log file (or upload it, after double checking that there is nothing sensitive). You can find the location of the log file in the About dialog.
